
<form id="top-bar-login">

  <div class="input-prepend">
    <span class="add-on"><i class="icon-user"></i></span>
    <?=$this->top_bar_form->user?>
  </div>

  <div class="input-prepend">
    <span class="add-on"><i class="icon-key"></i></span>
    <?=$this->top_bar_form->password?>
  </div>

  <a href="#" class="btn"><i class="icon-unlock"></i> <?=App::xlat('FORM_login')?></a>

</form>