<header>

  <div role="main" class="container-fluid main">

      <div class="row fit-to-design">
        <div class="span3"> &nbsp; </div>

        <div class="span7">
          <a class="top-menu hoteles round-bottom" href="<?=App::base()?>">
            <span class="ptg-hoteles"></span> Hoteles
          </a>
          <a class="top-menu restaurantes round-bottom" href="<?=App::base()?>">
            <span class="ptg-restaurantes"></span> Cafes & Restaurantes
          </a>
          <a class="top-menu antros round-bottom" href="<?=App::base()?>">
            <span class="ptg-antros"></span> Antros & Bares
          </a>
        </div>

        <div class="span2"> &nbsp; </div>

      </div>

  </div>

</header>