
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections contact-us">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-envelope"></span> <?=App::xlat('contact_us')?> </li>
      </ol>


      <div class="panel panel-default no-round addon-promotions">
        <div class="panel-heading no-round">
          <h3 class="panel-title"><span class="icon-envelope-alt"></span> <?=App::xlat('contact_us')?></h3>
        </div>
        <div class="panel-body block-ui">

          <form id="contact">
            <div class="result"></div>
            <div class="input-append">
              <span class="add-on">
                <span class="the-icon icon-user"></span>
              </span>
              <?=$this->form->name?>
            </div>
            <div class="input-append">
              <span class="add-on">
                <span class="the-icon icon-envelope-alt"></span>
              </span>
              <?=$this->form->email?>
            </div>
            <div class="input-append">
              <span class="add-on">
                <span class="the-icon icon-comments-alt"></span>
              </span>
              <?=$this->form->comments?>
            </div>
            <div class="input-append">
              <span class="add-on">
                <span class="the-icon icon-unlock"></span>
              </span>
              <?=$this->form->captcha?>
              <span id="captcha-refresh" class="icon-refresh" title="<?=App::xlat('captcha_generate')?>"></span>
              <?=$this->form->button?>
            </div>
          </form>

        </div>
      </div>


    </div>


    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>