
  <div class="container">
    <article class="row">

      <section class="three fifths right-one padded no-top-pad mini">

          <?=App::module('Addons')->renderBlock("site/index","top-menu")?>

          <?=App::module('Articles')->renderBlock("index","city-images", array('city'=> 'mazatlan' ))?>

          <div class="tabs mar-right daEvents">
            <ul>
              <li><a href="#daEvents" class="active events"><img src="<?=App::media( '/images/mobile/eventos.jpg' )?>" /></a></li>
            </ul>
            <div id="daEvents" class="active events">
              <?=App::module('Articles')->renderBlock("events/index","events")?>
            </div>
          </div>

          <div class="tabs daNews">
            <ul>
              <li><a href="#daNews" class="news"><img src="<?=App::media( '/images/mobile/noticias.jpg' )?>" /></a></li>
            </ul>
            <div id="daNews" class="active news">
              <?=App::module('Articles')->renderBlock("index","latest")?>
            </div>
          </div>


      </section>
      <aside class="one fifth left-three mini">
        <?=App::module('Addons')->renderBlock("site/index","logo")?>
        <div class="no-movil">
          <?=App::module('Addons')->renderBlock("site/index","menu")?>
        </div>
      </aside>
      <aside class="one fifth mini">
        <?=App::module('Addons')->renderBlock("site/index","promotions")?>
      </aside>
    </article>

  </div>