
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>



    <div class="col-lg-6 col-sm-6 sections">
      <?=App::module('Addons')->renderBlock("site/index","top-menu")?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-phone-sign"></span> <?=App::xlat('phone_sos')?> </li>
      </ol>

      <h3><?=App::xlat('phone_sos')?></h3>

        <table class="table well table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Dependencia</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td> 066 </td>
              <td> Emergencias </td>
            </tr>
            <tr>
              <td> 072 </td>
              <td> Servicios Públicos </td>
            </tr>
            <tr>
              <td> 073 </td>
              <td> JUMAPAM </td>
            </tr>
            <tr>
              <td> 071 </td>
              <td> CFE </td>
            </tr>
            <tr>
              <td> 983.99.20 / 981.27.69 </td>
              <td> Bomberos </td>
            </tr>
            <tr>
              <td> 983.28.16 </td>
              <td> Tránsito </td>
            </tr>
            <tr>
              <td> 080 </td>
              <td> Policía Municipal </td>
            </tr>
            <tr>
              <td> 985.53.11 </td>
              <td> Policia Ministerial </td>
            </tr>
            <tr>
              <td> 066 </td>
              <td> Protección Civil </td>
            </tr>
            <tr>
              <td> 984.78.41 </td>
              <td> IMSS </td>
            </tr>
            <tr>
              <td> 986.33.43 </td>
              <td> ISSSTE </td>
            </tr>
            <tr>
              <td> 981.36.90 </td>
              <td> Cruz Roja </td>
            </tr>
            <tr>
              <td> 983.45.70 </td>
              <td> Hospital Municipal </td>
            </tr>
            
            <tr>
              <td> 984.00.58 </td>
              <td> Hospital General </td>
            </tr>
            
            <tr>
              <td> 981.34.56 </td>
              <td> Centro de Salud </td>
            </tr>

          </tbody>
        </table>

    </div>



    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","promotions")?>
    </div>
    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>