
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections register">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-user"></span> <?=App::xlat('register')?> </li>
      </ol>

      <div class="panel panel-default no-round addon-promotions">
        <div class="panel-heading no-round">
          <h3 class="panel-title"><span class="icon-envelope-alt"></span> <?=App::xlat('register')?></h3>
        </div>
        <div class="panel-body block-ui">

          <form id="register">
            <div class="result"></div>

            <div class="form-group">
              <label class="col-lg-1 control-label" for="business"><span class="icon-hospital"></span></label>
              <div class="col-lg-11">
                <?=$this->form->business?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-1 control-label" for="name"><span class="icon-user"></span></label>
              <div class="col-lg-11">
               <?=$this->form->name?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-1 control-label" for="email"><span class="icon-envelope-alt"></span></label>
              <div class="col-lg-11">
                <?=$this->form->email?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-1 control-label" for="comments"><span class="icon-comments-alt"></span></label>
              <div class="col-lg-11">
                <?=$this->form->comments?>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-1 control-label" for="captcha-input"><span class="icon-unlock"></span></label>
              <?=$this->form->captcha?>
              <span id="captcha-refresh" class="icon-refresh" title="<?=App::xlat('captcha_generate')?>"></span>
              <?=$this->form->button?>
            </div>
          </form>

        </div>
      </div>

    </div>

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>
