
<div role="main" class="container-fluid main">

    <div class="row-fluid fit-to-design">
      <div class="span3">
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
      </div>

      <div class="span7">
        <div class="page-section"> <?=$this->article['article']?> </div>
      </div>

      <div class="span2">
        <?=App::module('Addons')->renderBlock("site/index","banner-right")?>
      </div>

    </div>

</div>