
  <div class="business-register">
    <div id="sidebar"> <img src="<?=App::media('/images/places-to-go-logo.png')?>" title="<?=App::getConfig('website_name')?>" alt="<?=App::getConfig('website_name')?>" /> </div>

      <?php if( $this->response > 0 ): ?>
        <h3><?=App::xlat('registered_business')?></h3>
        <p class="br-success"> <?=App::xlat('registered_business_desc')?> </p> 
        <a href="<?=App::www()?>" class="btn btn-success">
          <i class="icon-external-link icon-large"></i> 
          <?=App::xlat('main_page')?>
        </a>

      <?php else: ?>

        <h3 class="title">Registro de empresa</h3>
        <form id="business-register" method="post" enctype="application/x-www-form-urlencoded">
        <?=$this->form->city?>

          <fieldset id="br-access">
            <legend><?=App::xlat('access_data')?></legend>
            <div class="input-append">
              <span class="add-on">
                <i class="icon-envelope"></i>
              </span>
              <?=$this->form->user?>
            </div>
            <div class="input-append">
              <span class="add-on">
                <i class="icon-lock"></i>
              </span>
              <?=$this->form->password?>
            </div>
          </fieldset>

          <fieldset id="br-info">
            <legend><?=App::xlat('business_data')?></legend>
            <div class="input-append">
              <span class="add-on">
                <i class="icon-briefcase"></i>
              </span>
              <?=$this->form->name?>
            </div>
            <div class="input-append">
              <span class="add-on">
                <i class="icon-phone"></i>
              </span>
              <?=$this->form->phone?>
            </div>
            <div class="input-append">
              <span class="add-on">
                <i class="icon-map-marker"></i>
              </span>
              <?=$this->form->address?>
            </div>
          </fieldset>

          <div class="captcha">
            <?=$this->form->captcha?>
            <span id="captcha-refresh" class="icon-refresh" title="<?=App::xlat('captcha_generate')?>"></span>
            <?=$this->form->button?>
          </div>

        </form>

      <?php endif; ?>

  </div>

