<div class="login">
  <div id="sidebar"> <img src="<?=App::media('/images/places-to-go-logo.png')?>" title="<?=App::getConfig('website_name')?>" alt="<?=App::getConfig('website_name')?>" /> </div>
  <form id="login" method="post" enctype="application/x-www-form-urlencoded">
    <div class="input-append">
      <span class="add-on">
        <i class="icon-user"></i>
      </span>
      <?=$this->form->user?>
    </div>
    <div class="input-append">
      <span class="add-on">
        <i class="icon-lock"></i>
      </span>
      <?=$this->form->password?>
    </div>
    <?=$this->form->captcha?>
    <span id="captcha-refresh" class="icon-refresh" title="<?=App::xlat('captcha_generate')?>"></span>
    <?=$this->form->button?>
  </form>
</div>