
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>



    <div class="col-lg-6 col-sm-6 sections">
      <?=App::module('Addons')->renderBlock("site/index","top-menu")?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-key"></span> <?=App::xlat('login')?> </li>
      </ol>

      <h3><?=App::xlat('login')?></h3>

      <div class="login">
        <div id="sidebar"> <img src="<?=App::media('/images/places-to-go-logo.png')?>" title="<?=App::getConfig('website_name')?>" alt="<?=App::getConfig('website_name')?>" /> </div>
        <form id="login" method="post" enctype="application/x-www-form-urlencoded">
          <div class="input-append">
            <span class="add-on">
              <i class="icon-user"></i>
            </span>
            <?=$this->form->user?>
          </div>
          <div class="input-append">
            <span class="add-on">
              <i class="icon-lock"></i>
            </span>
            <?=$this->form->password?>
          </div>
          <?=$this->form->captcha?>
          <span id="captcha-refresh" class="icon-refresh" title="<?=App::xlat('captcha_generate')?>"></span>
          <?=$this->form->button?>
        </form>
      </div>
      
    </div>



    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","promotions")?>
    </div>
    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>