
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>



    <div class="col-lg-6 col-sm-6 sections login">
      <?=App::module('Addons')->renderBlock("site/index","top-menu")?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-key"></span> <?=App::xlat('login')?> </li>
      </ol>

      <h3><?=App::xlat('login')?></h3>

      <div class="panel">
        <div class="panel-heading">
          <h3 class="panel-title"></h3>
        </div>
        <div class="panel-body">

          <form id="login" method="post" enctype="application/x-www-form-urlencoded" class="form-horizontal">
          
            <div class="form-group">
              <label for="inputEmail1" class="col-lg-2 control-label"><span class="icon-user"></span></label>
              <div class="col-lg-10">
                <?=$this->form->user?>
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword1" class="col-lg-2 control-label"><span class="icon-key"></span></label>
              <div class="col-lg-10">
                <?=$this->form->password?>
              </div>
            </div>
          
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <?=$this->form->captcha?>
              </div>
            </div>
          
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button type="button" class="btn btn-default" id="captcha-refresh"><?=App::xlat('captcha_generate')?></button>
                <button type="submit" class="btn btn-default btn-success"><?=App::xlat('login')?></button>
              </div>
            </div>
            
          </form>

        </div>
      </div>

    </div>



    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","promotions")?>
    </div>
    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>