
  <fieldset id="section_info">
  <legend><?=App::xlat('FIELDSET_town_description')?></legend>

    <dl class="element field-section_desc type-textarea">
      <dt class="label"></dt>
      <dd class="field">
        <?=$this->form->section_desc?>
        </dd>
    </dl>

    <span class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary " id="save_section">
      <span class="ui-button-text"><?=App::xlat('BUTTON_save')?></span>
      <span class="ui-button-icon-secondary ui-icon ui-icon-disk"></span>
    </span>
    <span class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary " id="cancel_section">
      <span class="ui-button-text"><?=App::xlat('BUTTON_close')?></span>
      <span class="ui-button-icon-secondary ui-icon ui-icon-cancel"></span>
    </span>

  </fieldset>