<?php
  // $design        = App::getDesign();
  // $frontend_skin = App::www().'/skin/'.$design->getCurrentPackage().'/'.$design->getCurrentTheme().'/'.App::getConfig('design')->defaults->frontend->skin;
?>
<head>
<title><?=isset($this->pageTitle) ? $this->pageTitle:@$this->xd['pageTitle'];?></title>
<meta charset="UTF-8" />
<meta name="author" content="<?=isset($this->pageAuthor) ? $this->pageAuthor:@$this->xd['pageAuthor'];?>" />
<meta name="copyright" content="<?=isset($this->pageCopyright) ? $this->pageCopyright:@$this->xd['pageCopyright'];?>" />
<meta name="description" content="<?=isset($this->pageDescription) ? $this->pageDescription:@$this->xd['pageDescription'];?>" />
<meta name="keywords" content="<?=isset($this->pageKeywords) ? $this->pageKeywords:@$this->xd['pageKeywords'];?>" />
<meta name="Locality" content="Mazatlan, Mexico" />
<meta name="lang" content="es" />
<meta name="revisit-after" content="15 days" />

<!--Links-->
  <link href="<?=App::getDesign()->getRelativeSkinPath('/css/error.css');?>" rel="stylesheet" />

    <?= App::header()->getLinks();?>

    <?=@$this->xd['_block']['links'];?>

<!--Scripts-->
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-1.9.1.min.js','js');?>" ></script>
    <script>
      var baseUrl="<?=App::base();?>";
      var wwwUrl="<?=App::www();?>";
      var skinUrl="<?=App::skin();?>";
      var curLang="<?=App::locale()->getLang();?>";

      jQuery(document).ready(function(){
      });
		</script>

	<?=@$this->xd['_block']['add'];?>

	<?=App::header()->getCode();?>

</head>