<?php
  $date = App::module('Core')->getModel('Dates');
  $class = true;
?>

<section>
  <ul class="nav nav-tabs events">
    <li class="active round-top"><a href="#tab_events" data-toggle="tab"> <img src="<?=App::media( '/images/mobile/eventos.png' )?>" /> </a></li>
  </ul>
  <ul class="tab-content events_content round-bottom">
    <li class="tab-pane active" id="tab_events">

      <ul class="nav nav-tabs top-pad-20 nested_events">
        <li><a href="#n1" data-toggle="tab" class="today active"> <img class="img-responsive" src="<?=App::media( '/images/mobile/hoy.png' )?>" /> </a></li>
        <li><a href="#n2" data-toggle="tab" class="tomorrow"> <img class="img-responsive" src="<?=App::media( '/images/mobile/manana.png' )?>" /> </a></li>
        <li><a href="#n3" data-toggle="tab" class="month"> <img class="img-responsive" src="<?=App::media( '/images/mobile/mensual.png' )?>" /> </a></li>
      </ul>
      <ul class="tab-content nested_events_content pad-bottom-20 pad-right-20">

        <li class="tab-pane round-bottom active <?=$this->mobile?>" id="n1">
          <?php if( ! empty($this->today) ): ?>
            <?php $class=true;?>
            <?php foreach($this->today AS $today): ?>
              <article <?php if(empty($class)){ echo 'class="zebra-on"'; $class=true; }else{$class=null;}?>>

                <h5> <a href="<?=App::www( App::xlat('eventos_singular' ) ."/". $today['seo']  )?>"> <?=$today['title']?> </a> </h5>
                <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
                <figure>
                  <?php if( file_exists( WP.DS.'media'.DS.$today['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                    <?php $img = App::media( $today['folder']."/gallery/listing.jpg" ); ?>
                  <?php else: ?>
                    <?php $img = App::media('/images/article-preview-listing.jpg'); ?>
                  <?php endif; ?>
                  <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $today['seo']  )?>">
                    <img class="img-responsive" src="<?=$img?>" alt="<?=$today['title']?>" title="<?=$today['title']?>" />
                  </a>
                  <figcaption>
                    <span class="icon-home"></span> <?=$today['address']?> <br />
                    <span class="icon-calendar"></span> <?=$date->toDate(3, $today['event_date'])?> | <span class="icon-time"></span> <?=$today['event_hours']?>
                  </figcaption>

                </figure>
              </article>
            <?php endforeach; ?>

          <?php else: ?>
            <article>
              <h6><span class="icon-search"></span> <?=App::xlat('no_data_found')?></h6>
            </article>
          <?php endif; ?>
        </li>


        <li class="tab-pane round-bottom <?=$this->mobile?>" id="n2">
          <?php if( ! empty($this->tomorrow) ): ?>
            <?php $class=true;?>
            <?php foreach($this->tomorrow AS $tomorrow): ?>
              <article <?php if(empty($class)){ echo 'class="zebra-on"'; $class=true; }else{$class=null;}?>>

                <h5> <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $tomorrow['seo']  )?>"> <?=$tomorrow['title']?> </a> </h5>
                <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
                <figure>
                  <?php if( file_exists( WP.DS.'media'.DS.$tomorrow['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                    <?php $img = App::media( $tomorrow['folder']."/gallery/listing.jpg" ); ?>
                  <?php else: ?>
                    <?php $img = App::media('/images/article-preview-listing.jpg'); ?>
                  <?php endif; ?>
                  <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $tomorrow['seo']  )?>">
                    <img class="img-responsive" src="<?=$img?>" alt="<?=$tomorrow['title']?>" title="<?=$tomorrow['title']?>" />
                  </a>
                  <figcaption>
                    <span class="icon-home"></span> <?=$tomorrow['address']?> <br />
                    <span class="icon-calendar"></span> <?=$date->toDate(3, $tomorrow['event_date'])?> | <span class="icon-time"></span> <?=$tomorrow['event_hours']?>
                  </figcaption>

                </figure>
              </article>
            <?php endforeach; ?>

          <?php else: ?>
            <article>
              <h6><span class="icon-search"></span> <?=App::xlat('no_data_found')?></h6>
            </article>
          <?php endif; ?>
        </li>


        <li class="tab-pane round-bottom <?=$this->mobile?>" id="n3">
          <?php if( ! empty($this->month) ): ?>
            <?php $class=true;?>
            <?php foreach($this->month AS $month): ?>
              <article <?php if(empty($class)){ echo 'class="zebra-on"'; $class=true; }else{$class=null;}?>>

                <h5> <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $month['seo']  )?>"> <?=$month['title']?> </a> </h5>
                <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
                <figure>
                  <?php if( file_exists( WP.DS.'media'.DS.$month['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                    <?php $img = App::media( $month['folder']."/gallery/listing.jpg" ); ?>
                  <?php else: ?>
                    <?php $img = App::media('/images/article-preview-listing.jpg'); ?>
                  <?php endif; ?>
                  <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $month['seo']  )?>">
                    <img class="img-responsive" src="<?=$img?>" alt="<?=$month['title']?>" title="<?=$month['title']?>" />
                  </a>
                  <figcaption>
                    <span class="icon-home"></span> <?=$month['address']?> <br />
                    <span class="icon-calendar"></span> <?=$date->toDate(3, $month['event_date'])?> | <span class="icon-time"></span> <?=$month['event_hours']?>
                  </figcaption>

                </figure>
              </article>
            <?php endforeach; ?>

          <?php else: ?>
            <article>
              <h6><span class="icon-search"></span> <?=App::xlat('no_data_found')?></h6>
            </article>
          <?php endif; ?>
        </li>

      </ul>

    </li>
  </ul>
</section>
