<?php
  $date = App::module('Core')->getModel('Dates');
  $class = true;
?>

<section>
  <ul class="nav nav-tabs events">
    <li class="active round-top"><a href="#tab_events" data-toggle="tab"> <img src="<?=App::media( '/images/mobile/eventos.png' )?>" /> </a></li>
  </ul>
  <ul class="tab-content events_content round-bottom">
    <li class="tab-pane active" id="tab_events">

      <ul class="nav nav-tabs top-pad-20 nested_events">
        <li><a href="#n1" data-toggle="tab" class="today active"> <img class="img-responsive" src="<?=App::media( '/images/mobile/hoy.png' )?>" /> </a></li>
        <li><a href="#n2" data-toggle="tab" class="tomorrow"> <img class="img-responsive" src="<?=App::media( '/images/mobile/manana.png' )?>" /> </a></li>
        <li><a href="#n3" data-toggle="tab" class="month"> <img class="img-responsive" src="<?=App::media( '/images/mobile/mensual.png' )?>" /> </a></li>
      </ul>
      <ul class="tab-content nested_events_content pad-bottom-20 pad-right-20">

        <li class="tab-pane round-bottom active <?=$this->mobile?>" id="n1">

          <?php if( ! empty($this->today) ): ?>
            <?php foreach($this->today AS $today): ?>
              <article class="events_today <?php if(empty($class)){ echo 'zebra-on'; $class=true; }else{$class=null;}?> ">
                 <h3>
                  <a class="events_link" href="<?=App::www( App::xlat( $today['type'].'_singular' ) ."/". $today['seo']  )?>">
                    <?=$today['title']?>
                  </a>
                </h3>
                <?php if( file_exists( WP.DS.'media'.DS.$today['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                  <a href="<?=App::www( App::xlat( $today['type'].'_singular' ) ."/". $today['seo']  )?>">
                    <img src="<?=App::media( $today['folder']."/gallery/aside-big.jpg" )?>" alt="<?=$today['title']?>" title="<?=$today['title']?>" />
                  </a>
                <?php else: ?>
                  <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $today['seo']  )?>">
                    <img src="<?=App::media( '/images/article-preview-listing.jpg' )?>" alt="<?=$today['title']?>" title="<?=$today['title']?>" />
                  </a>
                <?php endif;?>
                <div class="event_list_info">
                  <span class="icon-home  gray"></span> <?=$today['address']?>
                  <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span>  <span class="icon-calendar gray"></span> <?=App::locale()->toDate( $today['event_date'] ,'long')?>
                  <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span>  <span class="icon-time gray"></span> <?=$today['event_hours']?>
                </div>
              </article>
            <?php endforeach; ?>
          <?php else: ?>
            <article class="events_today">
              <h6>No se han encontrado eventos para hoy</h6>
            </article>
          <?php endif; ?>

        </li>


        <li class="tab-pane round-bottom <?=$this->mobile?>" id="n2">
          <?php if( ! empty($this->tomorrow) ): ?>
           <?php $class=true;?>
            <?php foreach($this->tomorrow AS $tomorrow): ?>
              <article class="events_tomorrow <?php if(empty($class)){ echo 'zebra-on'; $class=true; }else{$class=null;}?> ">
                 <h3>
                  <a class="tomorrow-topic" href="<?=App::www( App::xlat( $tomorrow['type'].'_singular' ) ."/". $tomorrow['seo']  )?>">
                    <?=$tomorrow['title']?>
                  </a>
                </h3>
                <?php if( file_exists( WP.DS.'media'.DS.$tomorrow['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                  <a href="<?=App::www( App::xlat( $tomorrow['type'].'_singular' ) ."/". $tomorrow['seo']  )?>">
                    <img src="<?=App::media( $tomorrow['folder']."/gallery/listing.jpg" )?>" alt="<?=$tomorrow['title']?>" title="<?=$tomorrow['title']?>" />
                  </a>
                <?php else: ?>
                  <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $tomorrow['seo']  )?>">
                    <img src="<?=App::media( '/images/article-preview-listing.jpg' )?>" alt="<?=$tomorrow['title']?>" title="<?=$tomorrow['title']?>" />
                  </a>
                <?php endif;?>
                <div class="event_list_info">
                  <span class="icon-home gray"></span> <?=$tomorrow['address']?>
                  <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span>  <span class="icon-calendar gray"></span> <?=App::locale()->toDate( $tomorrow['event_date'] ,'long')?>
                  <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span>  <span class="icon-time gray"></span> <?=$tomorrow['event_hours']?>
                </div>
              </article>
            <?php endforeach; ?>
          <?php else: ?>
            <article class="events_tomorrow">
              <h6>No se han encontrado eventos para esta fecha</h6>
            </article>
          <?php endif; ?>
        </li>


        <li class="tab-pane round-bottom <?=$this->mobile?>" id="n3">
          <?php if( ! empty($this->month) ): ?>
            <?php $class=true;?>
            <?php foreach($this->month AS $month): ?>
              <article class="events_month <?php if(empty($class)){ echo 'zebra-on'; $class=true; }else{$class=null;}?> ">
                 <h5>
                  <a class="month-topic" href="<?=App::www( App::xlat( $month['type'].'_singular' ) ."/". $month['seo']  )?>">
                    <?=$month['title']?>
                  </a>
                </h5>
                <?php if( file_exists( WP.DS.'media'.DS.$month['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                  <a href="<?=App::www( App::xlat( $month['type'].'_singular' ) ."/". $month['seo']  )?>">
                    <img class="img-responsive" src="<?=App::media( $month['folder']."/gallery/listing.jpg" )?>" alt="<?=$month['title']?>" title="<?=$month['title']?>" />
                  </a>
                <?php else: ?>
                  <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $month['seo']  )?>">
                    <img class="img-responsive" src="<?=App::media( '/images/article-preview-listing.jpg' )?>" alt="<?=$month['title']?>" title="<?=$month['title']?>" />
                  </a>
                <?php endif;?>
                <div class="event_list_info">
                  <span class="icon-home gray"></span> <?=$month['address']?>
                  <br class="show-when-small" /> <span class="hide-from-small">|</span>  <span class="icon-calendar gray"></span> <?=App::locale()->toDate( $month['event_date'] ,'long')?>
                  <br class="show-when-small" /> <span class="hide-from-small">|</span>  <span class="icon-time gray"></span> <?=$month['event_hours']?>
                </div>
              </article>
            <?php endforeach; ?>
    
          <?php else: ?>
            <article class="events_month">
              <h6>No se han encontrado eventos para este mes</h6>
            </article>
          <?php endif; ?>
        </li>

      </ul>

    </li>
  </ul>
</section>
