<?php
  $date = App::module('Core')->getModel('Dates');
  $class = true;
?>

<div class="panel panel-default no-round aside_block">
  <div class="panel-heading no-round">
    <h3 class="panel-title"><?=App::xlat('events_aside_block_title')?></h3>
  </div>
  <div class="panel-body">

    <ul class="nav nav-tabs events_w8">
      <li class="active"><a href="#today" data-toggle="tab" class="today"> <?=App::xlat('events_today')?> </a></li>
      <li><a href="#next" data-toggle="tab" class="next"> <?=App::xlat('events_next')?> </a></li>
      <li><a href="#past" data-toggle="tab" class="past"> <?=App::xlat('events_past')?> </a></li>
    </ul>
    <ul class="tab-content events_w8_content">

      <li class="tab-pane active <?=$this->mobile?>" id="today">

        <?php if( ! empty($this->today) ): ?>
          <?php $class=true;?>
          <?php foreach($this->today AS $today): ?>
            <article>

              <h5> <a href="<?=App::www( App::xlat('eventos_singular' ) ."/". $today['seo']  )?>"> <?=$today['title']?> </a> </h5>
              <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
              <figure>
                <?php if( file_exists( WP.DS.'media'.DS.$today['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                  <?php $img = App::media( $today['folder']."/gallery/listing.jpg" ); ?>
                <?php else: ?>
                  <?php $img = App::media('/images/article-preview-listing.jpg'); ?>
                <?php endif; ?>
                <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $today['seo']  )?>">
                  <img class="img-responsive" src="<?=$img?>" alt="<?=$today['title']?>" title="<?=$today['title']?>" />
                </a>
                <figcaption>
                  <span class="icon-home"></span> <?=$today['address']?> <br />
                  <span class="icon-calendar"></span> <?=$date->toDate(3, $today['event_date'])?> | <span class="icon-time"></span> <?=$today['event_hours']?>
                </figcaption>

              </figure>
            </article>
          <?php endforeach; ?>

        <?php else: ?>
          <article>
            <h6><span class="icon-search"></span> <?=App::xlat('no_data_found')?></h6>
          </article>
        <?php endif; ?>

        <a href="<?=App::www( App::xlat('eventos') )?>" class="btn btn-default btn-xs top-mar-20"> <?=App::xlat('view_more')?> <span class="icon-chevron-right"></span> </a>

      </li>


      <li class="tab-pane <?=$this->mobile?>" id="next">

        <?php if( ! empty($this->next) ): ?>
          <?php $class=true;?>
          <?php foreach($this->next AS $next): ?>
            <article>

              <h5> <a href="<?=App::www( App::xlat('eventos_singular' ) ."/". $next['seo']  )?>"> <?=$next['title']?> </a> </h5>
              <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
              <figure>
                <?php if( file_exists( WP.DS.'media'.DS.$next['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                  <?php $img = App::media( $next['folder']."/gallery/listing.jpg" ); ?>
                <?php else: ?>
                  <?php $img = App::media('/images/article-preview-listing.jpg'); ?>
                <?php endif; ?>
                <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $next['seo']  )?>">
                  <img class="img-responsive" src="<?=$img?>" alt="<?=$next['title']?>" title="<?=$next['title']?>" />
                </a>
                <figcaption>
                  <span class="icon-home"></span> <?=$next['address']?> <br />
                  <span class="icon-calendar"></span> <?=$date->toDate(3, $next['event_date'])?> | <span class="icon-time"></span> <?=$next['event_hours']?>
                </figcaption>

              </figure>
            </article>
          <?php endforeach; ?>

        <?php else: ?>
          <article>
            <h6><span class="icon-search"></span> <?=App::xlat('no_data_found')?></h6>
          </article>
        <?php endif; ?>

        <a href="<?=App::www( App::xlat('eventos') )?>" class="btn btn-default btn-xs top-mar-20"> <?=App::xlat('view_more')?> <span class="icon-chevron-right"></span> </a>
  
      </li>
  
  
      <li class="tab-pane <?=$this->mobile?>" id="past">
        <?php if( ! empty($this->past) ): ?>
          <?php $class=true;?>
          <?php foreach($this->past AS $past): ?>
            <article <?php if(empty($class)){ echo 'class="zebra-on"'; $class=true; }else{$class=null;}?>>

              <h5> <a href="<?=App::www( App::xlat('eventos_singular' ) ."/". $past['seo']  )?>"> <?=$past['title']?> </a> </h5>
              <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
              <figure>
                <?php if( file_exists( WP.DS.'media'.DS.$past['folder'].DS.'gallery'.DS.'listing.jpg' ) ): ?>
                  <?php $img = App::media( $past['folder']."/gallery/listing.jpg" ); ?>
                <?php else: ?>
                  <?php $img = App::media('/images/article-preview-listing.jpg'); ?>
                <?php endif; ?>
                <a href="<?=App::www( App::xlat( 'eventos_singular' ) ."/". $past['seo']  )?>">
                  <img class="img-responsive" src="<?=$img?>" alt="<?=$past['title']?>" title="<?=$past['title']?>" />
                </a>
                <figcaption>
                  <span class="icon-home"></span> <?=$past['address']?> <br />
                  <span class="icon-calendar"></span> <?=$date->toDate(3, $past['event_date'])?> | <span class="icon-time"></span> <?=$past['event_hours']?>
                </figcaption>

              </figure>
            </article>
          <?php endforeach; ?>

        <?php else: ?>
          <article>
            <h6><span class="icon-search"></span> <?=App::xlat('no_data_found')?></h6>
          </article>
        <?php endif; ?>

        <a href="<?=App::www( App::xlat('eventos') )?>" class="btn btn-default btn-xs top-mar-20"> <?=App::xlat('view_more')?> <span class="icon-chevron-right"></span> </a>

      </li>

    </ul>

  </div>
</div>