
<?php if( ! empty($this->promote) ): ?>

  <?php $date = App::module('Core')->getModel('Dates'); ?>

  <div class="carousel-promote-described">
    <div class="carousel carousel-fade slide promote-carousel" id="events-described-carousel">
      <div class="carousel-inner">
      <?php $first=true; ?>
      <?php foreach($this->promote AS $promote):?>
        <div class="item promote-described<?=($first===true)? ' active':null ?>">
          <h1><?=$promote['title']?></h1>
          <a href="<?=App::base( App::xlat( 'eventos_singular' ) ."/". $promote['seo']  )?>" class="btn btn-info pull-right">
            <span class="icon-file-alt"></span> <?=App::xlat('read_more')?>
          </a>
          <img src="<?=App::media( $promote['folder'].'gallery/promote.jpg' )?>" alt="<?=$promote['title']?>" title="<?=$promote['title']?>" />
        </div>
        <?php $first=false;?>
      <?php endforeach;?>
      </div>

      <div class="pull-right promote-nav">
        <a data-slide="prev" href="#events-described-carousel">
          <i class="icon-chevron-left"></i>
        </a>
        <a data-slide="next" href="#events-described-carousel">
          <i class="icon-chevron-right"></i>
        </a>
      </div>

    </div>



  </div>
  <div class="aside-block-shadow"></div>

<?php endif; ?>
