
<div role="main" class="container-fluid article">

    <div class="row-fluid fit-to-design">

      <div class="span3">
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
        <?=App::module('Addons')->renderBlock("site/index","banner-right")?>
      </div>

      <div class="span9">

       <?php if( ! empty($this->lodging['items']) ): ?>
         <?php $dates = App::module('Core')->getModel('Dates'); ?>
         
         <div class="articles">
         <?php foreach($this->lodging['items'] AS $lodging): ?>
           <?php $created = $dates->toDate( 11, $lodging['created']); ?>
            <article class="list">
              <h1><a href="<?=App::base( App::xlat( 'dormir_en' ) ."/". $lodging['seo']  )?>"><?=$lodging['title']?></a></h1>
              <?php if( file_exists( WP.DS.'media'.DS.$lodging['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
                <a href="<?=App::base( App::xlat( 'dormir_en' ) ."/". $lodging['seo']  )?>">
                  <img src="<?=App::media( $lodging['folder']."/gallery/article.jpg" )?>" alt="<?=$lodging['title']?>" title="<?=$lodging['title']?>" />
                </a>
              <?php else: ?>
                <a href="<?=App::base( App::xlat( 'dormir_en' ) ."/". $lodging['seo']  )?>">
                  <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$lodging['title']?>" title="<?=$lodging['title']?>" />
                </a>
              <?php endif;?>

              <div class="post-info">                        
                <div class="date">
                  <span class="month"><?=$dates->translate_date($created['month'],1)?></span>
                  <span class="day"><?=$created['day']?></span>
                  <span class="year"><?=$created['year']?></span>
                </div>                    
              </div>
              <div class="post-content">    
                <p><?=strip_tags($lodging['article'])?></p>
              </div>

              <p class="span pull-right info">
                <span class="icon-calendar"></span> <?=App::locale()->toDate( $this->article['publicated'] ,'long')?> |
                <span class="icon-user"></span> <?=$lodging['author']?> 
                <?php if( App::getEnvironment()!=='devel' ):?>
                  | <span class="icon-comments"></span> <fb:comments-count href="<?=App::base( App::xlat('articulos_singular').'/'. $lodging['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                <?php endif;?>
              </p>

            </article>

         <?php endforeach; ?>

         <?= empty($this->lodging['pagination_html']) ? '' : $this->lodging['pagination_html'];?>

       <?php else:?>

       <?php endif;?>

      </div>

    </div>

  </div>

</div>