  <div class="vertical-banner"> 
    <img src="<?=App::media('/banners/2013/03/banner-1.jpg')?>" alt="" title="">
    <img src="<?=App::media('/banners/2013/03/banner-2.jpg')?>" alt="" title="">
    <img src="<?=App::media('/banners/2013/03/banner-3.jpg')?>" alt="" title="">
    <img src="<?=App::media('/banners/2013/03/banner-4.jpg')?>" alt="" title="">
    <img src="<?=App::media('/banners/2013/03/banner-5.jpg')?>" alt="" title="">
    <img src="<?=App::media('/banners/2013/03/banner-6.jpg')?>" alt="" title="">
    <img src="<?=App::media('/banners/2013/03/banner-7.jpg')?>" alt="" title="">
  </div> 