
  <div class="cloud-<?=$this->direction?> <?=$this->direction==='left'? 'to-right':null?>">

  <?php if( $this->direction==='left' ): ?>

    <?php for($i = 1; $i<=6; $i++): ?>
      <?php for($tags = 1; $tags<=25; $tags++): ?>
        <a href="<?=App::base( App::xlat('tag_url_' . $tags) )?>" rel="<?=App::xlat('tag_rel_' . $tags)?>"> <?=App::xlat('tag_name_' . $tags)?> </a>
      <?php endfor;?>
    <?php endfor;?>

  <?php else:?>

    <?php for($i = 1; $i<=6; $i++): ?>
      <?php for($tags = 25; $tags>=1; $tags--): ?>
        <a href="<?=App::base( App::xlat('tag_url_' . $tags) )?>" rel="<?=App::xlat('tag_rel_' . $tags)?>"> <?=App::xlat('tag_name_' . $tags)?> </a>
      <?php endfor;?>
    <?php endfor;?>

  <?php endif; ?>

  </div>