<div class="block site_operation_hours">
  <h1>
    <?=App::xlat('CONTACT_OPERATION_HOURS_title')?>
    <span><?=App::xlat('CONTACT_OPERATION_HOURS_subtitle')?></span>
  </h1>

  <strong> <?=App::xlat('dates_long_day_1')?> </strong>
  <ul class="monday">
    <li><?=App::xlat('OPERATION_HOURS_MONDAY_leader')?></li>
    <li><?=App::xlat('OPERATION_HOURS_MONDAY_pray')?></li>
  </ul>

  <strong> <?=App::xlat('dates_long_day_6')?> </strong>
  <ul class="saturday">
    <li><?=App::xlat('OPERATION_HOURS_SATURDAY_children_class')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SATURDAY_teens_class')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SATURDAY_youth_meeting')?></li>
  </ul>

  <strong> <?=App::xlat('OPERATION_HOURS_SUNDAY_service')?> </strong>
  <ul class="sunday">
    <li><?=App::xlat('OPERATION_HOURS_SUNDAY_morning')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SUNDAY_afternoon')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SUNDAY_evening')?></li>
  </ul>

</div>