
<div class="container hidden-sm">
  <div class="row">

    <div class="col-lg-3 col-sm-3 no-padding to-center-sm">
      <a class="top-menu hoteles round-bottom" href="<?=App::www('hoteles')?>">
        <img src="<?=App::media('/images/menu/hotel.png')?>" class="" />
        <img src="<?=App::media('/images/hoteles.png')?>" />
      </a>
    </div>
    <div class="col-lg-5 col-sm-5 no-padding to-center-sm">
      <a class="top-menu restaurantes round-bottom desktop-only" href="<?=App::www('cafes-y-restaurantes')?>">
        <img src="<?=App::media('/images/menu/restaurant.png')?>" class="" />
        <img src="<?=App::media('/images/cafes-restaurantes.png')?>" />
      </a>
    </div>
    <div class="col-lg-4 col-sm-4 no-padding to-center-sm">
      <a class="top-menu antros round-bottom desktop-only" href="<?=App::www('bares')?>">
        <img src="<?=App::media('/images/menu/bares.png')?>" />
        <img src="<?=App::media('/images/antros-bares.png')?>" />
      </a>
    </div>
  </div>
</div>