<?php if( ! empty($this->files) ): ?>
  <div id="<?=str_replace("#", "", $this->target)?>" class="carousel slide mar-top-botom-30">

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <?php $loop=0;?>
      <?php foreach($this->files AS $file):?>
        <div class="item <?=$loop==0?'active':null?> to-center">
          <img src="<?=App::media( $this->folder . $file )?>" alt="" title="" class="img-responsive" />
        </div>
        <?php $loop+=1; ?>
      <?php endforeach;?>
    </div>

    <!-- Indicators -->
    <ol class="carousel-indicators">
      <?php for($indicator=0; $indicator<=($loop-1); $indicator++): ?>
        <li data-target="<?=$this->target?>" data-slide-to="<?=$indicator?>" class="<?=$indicator==0?'active':null?>"></li>
      <?php endfor; ?>
    </ol>

    <!-- Controls -->
    <a class="left carousel-control" href="<?=$this->target?>" data-slide="prev">
      <span class="icon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="<?=$this->target?>" data-slide="next">
      <span class="icon-chevron-right"></span>
    </a>
  </div>
<?php endif; ?>