
<div role="main" class="container-fluid main">

  <div class="row-fluid fit-to-design">
    <div class="span8">
      <?=$this->article['article']?>
    </div>

    <div class="span4">
      <aside>
        <?=App::module('Addons')->renderBlock("site/index","social-networks", array("style" => "medium") )?>
        <?=App::module('Addons')->renderBlock("facebook/index","i-like-this")?>
        <?=App::module('Articles')->renderBlock("index","carousel-promote-described")?>
        <?=App::module('Articles')->renderBlock("announcement/index","carousel-promote")?>
      </aside>
    </div>

  </div>

</div>