
<div role="main" class="container-fluid main contact">

    <div class="row-fluid">
      <div class="span12">
        <div id="contact-map"></div>
      </div>
    </div>

    <div class="row-fluid fit-to-design contact-area">
      <div class="span8">

        <h1><?=App::xlat('form_leave_message')?></h1>
        <form class="well" id="contact">
          <div class="input-append pull-left">
            <span class="add-on">
              <i class="icon-user"></i>
            </span>
            <?=$this->form->name?>
          </div>
          <div class="input-append pull-right">
            <span class="add-on">
              <i class="icon-envelope-alt"></i>
            </span>
            <?=$this->form->email?>
          </div>
          <?=$this->form->comments?>
          <?=$this->form->captcha?>
          <span id="captcha-refresh" class="icon-refresh" title="<?=App::xlat('captcha_generate')?>"></span>
          <?=$this->form->button?>
        </form>

      </div>
      <div class="span4">
        <aside>
          <h1><?=App::xlat('contact_us')?></h1>

          <h2><?=App::xlat('address')?></h2>
          <p class="offset1"><i class="icon-road"></i> <?=App::xlat('address_full')?></p>

          <h2><?=App::xlat('hours')?></h2>
          <p class="offset1"><i class="icon-time"></i> <?=App::xlat('address_hours')?></p>

          <h2><?=App::xlat('phones')?></h2>
          <p class="offset1">
            <i class="icon-phone"></i> <?=App::xlat('address_phone_1')?> <br />
            <i class="icon-phone"></i> <?=App::xlat('address_phone_2')?>
          </p>

          <h2><?=App::xlat('contact_email')?></h2>
          <p class="offset1">
            <i class="icon-envelope"></i> oficina@placestogo.mx <br />
            <i class="icon-envelope"></i> admin@placestogo.mx <br />
            <i class="icon-envelope"></i> web@placestogo.mx
          </p>

        </aside>
      </div>
    </div>

</div>