
<div role="main" class="container-fluid main">

    <div class="row-fluid fit-to-design">
      <div class="span8">

        <div id="doctrine-carousel" class="carousel slide">
          <div class="carousel-inner">

            <div class="item active">
              <h1><span>Dios</span></h1>
              <img src="<?=App::media('/doctrinas/01-dios.jpg')?>" alt="Dios" title="Dios" />
              <p>Creemos que hay un solo Dios que se ha manifestado al mundo en distintas formas a través de las edades y que especialmente se ha revelado como Padre en la creación del universo, como Hijo en la redención de la humanidad y como Espíritu Santo derramándose en los corazones de los creyentes.</p>
              <p>Este Dios es el creador de todo lo que existe, sea visible o Invisible, eterno, infinito en poder, Santo en su naturaleza, atributos y propósitos y poseyendo una Divinidad absoluta e indivisible.</p>
              <p>Es infinito en su inmensidad, inconcebible en su modo de ser e indescriptible en su esencia; conocido completamente sólo por sí mismo, porque una mente infinita sólo ella puede comprender a sí misma.</p>
              <p>No tiene cuerpo ni partes y por lo tanto está libre de todas las limitaciones.</p>
              <p>"El primer mandamiento de todos es: Oye, Israel, el Señor nuestro Dios, el Señor uno es"( Deuteronomio 6:4; Marcos 12:29). "Para nosotros, sin embargo sólo hay un Dios..." (1 Corintios 8:5,6).</p>
            </div>
            
            <div class="item">
              <h1><span>Jesucristo</span></h1>
              <img src="<?=App::media('/doctrinas/02-jesucristo.jpg')?>" alt="Jesucristo" title="Jesucristo" />
              <p>Creemos que Jesucristo nació milagrosamente del vientre de la virgen María, por obra del Espíritu Santo, y que al mismo tiempo es el único y verdadero Dios (Romanos 9:5, 1 Juan 5:20).</p>
              <p>El mismo Dios del Antiguo Testamento tomó forma humana (Isaías 60:1-3). "Y aquel verbo fue hecho carne y habitó entre nosotros..." (Juan 1:14). "Y sin contradicción, grande es el misterio de la piedad: Dios ha sido manifestado en carne, ha sido justificado con el Espíritu; ha sido visto de los ángeles; ha sido predicado a los gentiles; ha sido creído en el mundo; ha sido recibido en gloria" (1 Timoteo 3:16). </p>
              <p>Creemos que en Jesucristo se mezclaron en una forma perfecta e incomprensible los atributos divinos y la naturaleza humana.</p>
              <ul>
              <li>Por parte de María, en cuyo vientre tomó forma de hombre, era humano.</li>
              <li>Por parte del Espíritu Santo, que fue el que lo engendró en María, era divino; por eso se le llama Hijo de Dios e Hijo de hombre.</li>
              </ul>
              <p>Por lo tanto, creemos que Jesucristo es Dios "Y que en él habita toda la plenitud de la Divinidad corporalmente" (Colosenses 2:9), y que la Biblia da a conocer todos los atributos:</p>
              <ul>
              <li>Es Padre Eterno, a la vez que es un niño que nos ha nacido (lsaías 9:6 ].</li>
              <li>Es creador de todo (Isaías 45:18; Colosenses l: 16,17).</li>
              <li>Es omnipresente (Deuteronomio 4:39; Juan 3:13).</li>
              <li>Hace maravillas como Dios Todopoderoso (Salmos 86:10; Lucas 5:24:26).</li>
              <li>Tiene potestad sobre el mar (Salmos 107:29,30; Marcos 4:37-39).</li>
              <li>Es el mismo siempre (Salmos 102:27; Hebreos 13:8).</li>
              </ul>
            </div>
            
            <div class="item">
              <h1><span>Espíritu Santo</span></h1>
              <img src="<?=App::media('/doctrinas/03-espiritu.jpg')?>" alt="Espíritu Santo" title="Espíritu Santo" />
              <p>Creemos en el bautismo del Espíritu Santo, prometido por Dios en el Antiguo Testamento y derramado después de la glorificación del Señor Jesucristo, que es quién lo envía ( Joel 2:28, 29; Juan 7:37-39; 14:16-26; Hechos 2:1-4).</p>
              <p>Creemos, además, que la demostración de que una persona ha sido bautizada con el Espíritu Santo, son las nuevas lenguas o idiomas en que el creyente puede hablar, y que esta señal es también para nuestro tiempo.</p>
              <p>Creemos también, que el Espíritu Santo es potencia que permite testificar de Cristo ( Hechos 1:8) y que sirve para la formación de un carácter cristiano más agradable a Dios ( Gálatas 5:22-25).</p>
              <p>El mismo Espíritu da dones a los hombres, que sirven para la edificación de la Iglesia ( Romanos 12:6-8; 1 Corintios 12:1-12; Efesios 4:7-13), <strong>pero no aceptamos que haya en ningún hombre la facultad de impartir algún don</strong>, pues "Pero todas estas cosas las hace uno y el mismo Espíritu, repartiendo a cada uno en particular como él quiere" ( 1 Corintios 12:11). "Y a cada uno es dada la gracia conforme a la medida del don de Cristo" ( Efesios 4:7). </p>
              <p>Todos los miembros de la Asamblea Apostólica de la Fe en Cristo Jesús, deben buscar el Espíritu Santo y tratar de vivir constantemente en el Espíritu, como lo recomienda la Palabra de Dios ( Romanos 8:5-16; Efesios 5:18; Colosenses 3:5).</p>
            </div>
            
            <div class="item">
              <h1><span>Resurreción de Jesucristo</span></h1>
              <img src="<?=App::media('/doctrinas/04-resurrecion-cristo.jpg')?>" alt="Resurreción de Jesucristo" title="Resurreción de Jesucristo" />
              <p>Creemos en la resurrección literal de nuestro Señor Jesucristo que se efectuó al tercer día de su muerte, como lo relatan los evangelistas ( Mateo 28:1-10; Marcos 16:1-20; Lucas 24:1-12; 36:44; Juan 20:1-18). </p>
              <p>Esta resurrección había sido anunciada por los profetas ( Isaías 53:12) y es necesaria para nuestra esperanza y justificación ( Romanos 4:25; 1 Corintios 15:20).</p>
            </div>
            
            <div class="item">
              <h1><span>Iglesia</span></h1>
              <img src="<?=App::media('/doctrinas/05-iglesia.jpg')?>" alt="Iglesia" title="Iglesia" />
              <p>Creemos que la Iglesia de nuestro Señor Jesucristo es una, universal e indivisible, formada por todos los hombres, sin distinción de nacionalidad, idioma, color o costumbres que hayan aceptado a nuestro Señor Jesucristo como Salvador y hayan sido bautizados en el cuerpo por e Espíritu Santo ( 1 Corintios 12:13). </p>
              <p>Los vínculos que unen a los miembros de la Iglesia son el amor y la fe comunes, y s estandarte o bandera es el nombre de Jesucristo, ante cuyo emblema marcha gallardamente la Iglesia imponente como ejército en orden ( Cantares 6:10).</p>
            </div>
            
            <div class="item">
              <h1><span>Iglesia y Estado</span></h1>
              <img src="<?=App::media('/doctrinas/06-iglesia-y-estado.jpg')?>" alt="Iglesia y Estado" title="Iglesia y Estado" />
              <p>Creemos en la separación del Estado y la Iglesia y que ninguno debe intervenir en los asuntos íntimos del otro, pues aquí se cumple el precepto bíblico de dar lo que es de César a César y lo que es de Dios a Dios ( Mateo 12:17).</p>
              <p>Los cristianos deben tomar participación en actividades cívicas de acuerdo con su capacidad e inclinaciones políticas, per siempre reflejando sus ideas personales y no las de la Iglesia, que siempre es neutral y tiene cabida para los hombres de todos los credos políticos. Al mismo tiempo, todos los cristianos deben obedecer las autoridades civiles y todas las leyes y disposiciones que de ellas emanen, siempre que no contradiga sus principios religiosos o los obliguen a hacer cosas en contra de su conciencia ( Romanos 13:1-7). </p>
            </div>
            
            <div class="item">
              <h1><span>Servicio Militar</span></h1>
              <img src="<?=App::media('/doctrinas/07-servicio-militar.jpg')?>" alt="Servicio Militar" title="Servicio Militar" />
              <p>La Asamblea Apostólica de la Fe en Cristo Jesús, reconoce el gobierno humano como de ordenación divina ( Romanos 13:1,2) y al hacerlo así, exhorta a sus miembros a que afirmen su lealtad a su patria. </p>
              <p>Siendo discípulos del Señor Jesucristo, es el deber de todo cristiano obedecer sus preceptos y mandamientos que enseñan como sigue: "No resistáis al mal" ( Mateo 5:39). "Tened paz con todos los hombres" ( Hebreos 12:14   También ( Mateo 26:52; Romanos 12:19; Santiago 5:6; Apocalipsis 13:10). Por estas escrituras, se cree y se interpreta que los seguidores de nuestro Señor Jesucristo no deben destruir propiedades ajenas o quitar vidas humanas. </p>
              <p>Se considera un pecado, que después de haber recibido el conocimiento de la verdad, haber sido perdonados de todos los pecados, y haber sido hechos nuevas criaturas en Cristo Jesús.</p>
              <p>Participar en acciones y actos diferentes a aquellos recomendados por la divina Palabra de Dios ( Hebreos 6:4-9; 10:26,27 ).</p>
              <p>Por lo tanto, todos los miembros son exhortados a responder voluntaria y libremente al llamado de su gobierno, en tiempo de paz o de guerra, y prestar servicio en todas las capacidades no combatientes. La doctrina enseña que se ore porque tengamos siempre hombres de Dios como gobernantes, y orar por ellos para que tengan siempre guianza divina, y para que como una nación, seamos guardados fuera de la guerra, con honor, y vivir en paz continuamente ( 1 Timoteo 2:1-3 ). </p>
            </div>
            
            <div class="item">
              <h1><span>Sistema Economico</span></h1>
              <img src="<?=App::media('/doctrinas/08-sistema-economico.jpg')?>" alt="Sistema Economico" title="Sistema Economico" />
              <p>Creemos que el sistema que la Biblia enseña para la obtención de fondos necesarios para el cumplimiento de la obra, es el de diezmos y ofrendas, y que debe ser practicado por ministros y creyentes igualmente ( Génesis 28:22; Malaquías 3:10; Mateo 23:23; Lucas 6:38; Hechos 11:27-30; 1 Corintios 9:3-15; 16:1,2; Gálatas 6:6-10; Filipenses 4:10-12; 1 Timoteo 5:17,18; Hebreos 13:16 ).</p>
              <p>Sabiendo que la obra de Dios no tan sólo tiene el aspecto espiritual, sino también el material, creernos que es necesario reglamentar la manera en que se adquieran y distribuyan los fondos necesarios para responder a las necesidades materiales de la obra. </p>
            </div>
            
            <div class="item">
              <h1><span>Cuerpo Ministerial</span></h1>
              <img src="<?=App::media('/doctrinas/09-cuerpo-ministerial.jpg')?>" alt="Cuerpo Ministerial" title="Cuerpo Ministerial" />
              <p>Creemos, también, que aunque el llamamiento al ministerio es de origen divino, la Palabra de Dios contiene suficientes enseñanzas sobre los requisitos que debe llenar la persona que vaya a servir en el ministerio, y que corresponde a los gobiernos eclesiásticos organizados examinar a los candidatos al ministerio y determinar cuándo son dignos de aprobación, y la tarea a que se deban dedicar ( Hechos 1:23-26; 6:1-3; 1 Timoteo 3:1-10; 4:14; 5:22; Tito 1:5-9 ).</p>
              <p>Creemos, además, que el Espíritu Santo usa al ministro en distintas formas, según las necesidades de la obra de Dios y la capacidad y disposición personal del ministro. Nadie puede ser colocado en una posición más elevada que aquella a que se haga merecedor ( Romanos 12:3; 1 Timoteo 3:13). </p>
              <p>Creemos que el obispado es el cargo más elevado en el ministerio, y que a quienes lo ocupan se les debe dar muestras especiales, consideraciones y respeto, sin menoscabo de los que ocupan posiciones de menor responsabilidad.</p>
            </div>
            
            <div class="item">
              <h1><span>Bautismo</span></h1>
              <img src="<?=App::media('/doctrinas/10-bautismo.jpg')?>" alt="Bautismo" title="Bautismo" />
              <p>Creemos en el bautismo e agua, por inmersión y en el nombre de Jesucristo, el cual debe ser administrado por un ministro ordenado. El bautismo debe ser por Inmersión, porque sólo así se representa la muerte del hombre al pecado, que debe ser semejante a la muerte de Cristo ( Romanos 6:1-5).</p>
              <p>Y en el nombre de Jesucristo, porque esta es la forma en que los apóstoles y ministros bautizaron en la edad primitiva de la Iglesia, según lo prueban las Sagradas Escrituras ( Hechos 2:38; 8:16; 10:48; 19:5; 22:16). </p>
            </div>
            
            <div class="item">
              <h1><span>Comunión</span></h1>
              <img src="<?=App::media('/doctrinas/11-comunion.jpg')?>" alt="Comunión" title="Comunión" />
              <p>Creemos en la práctica literal de la Cena del Señor, que él mismo instituyó ( Mateo 26:26-29; Marcos 14:22-25; Lucas 22:15-20; 1 Corintios 11:22-31 ).</p>
              <p>En esta ordenanza se debe usar pan sin levadura, que representa el cuerpo sin pecado de nuestro Señor Jesucristo, y vino sin fermentar, que representa la sangre de Cristo, que consumó nuestra redención.</p>
              <p>El objeto de esta ceremonia es conmemorar la muerte de nuestro Señor Jesucristo y anunciar el día en que regresará al mundo, y al mismo tiempo para dar testimonio de la comunión que existe entre los creyentes. Ninguna persona debe participar de este acto si no es miembro fiel de la Iglesia y está en plena comunión, pues al hacerlo sin cumplir estas condiciones, no podrá discernir el cuerpo del Señor ( 1 Corintios 10:15-17; 11:27,28; 2 Corintios 13:5 ).</p>
              <p>EI Señor, al terminar de tomar la cena con sus apóstoles celebró un acto que de momento los maravilló, y que fue el lavatorio de pies. Al terminar este acto, el maestro explicó a sus discípulos el significado de él, y les recomendó que se lavasen los pies los unos a los otros. La Iglesia practica este acto en combinación con la Cena del Señor o indistintamente, como un acto de humildad y confraternidad cristiana ( 1 Timoteo 5:10 ).</p>
            </div>
            
            <div class="item">
              <h1><span>Matrimonio</span></h1>
              <img src="<?=App::media('/doctrinas/12-matrimonio.jpg')?>" alt="Matrimonio" title="Matrimonio" />
              <p>Creemos que el matrimonio es sagrado, pues fue establecido desde el principio y es honroso en todos ( Génesis 2:21-24; Mateo 19:1-5; Hebreos 13:4 ). Los matrimonios deben verificarse de acuerdo con las leyes de los países respectivos y luego solemnizarse en la iglesia según la práctica aprobada. Las parejas que no hayan legalizado su unión y desean bautizarse, deben cumplir primeramente con los requisitos de las leyes civiles.</p>
              <p>Creemos que el matrimonio es una unión que debe perdurar mientras viven los dos cónyuges. Al morir uno de ellos, el otro está libre para casarse y no peca si lo hace en el Señor ( Romanos 7:1-3; 1 Corintios 7:39).</p>
              <p>Creemos, además, que los matrimonios deben verificarse exclusivamente entre los miembros fieles. Ningún ministro deberá casar a un miembro de la iglesia con una persona inconversa. Los miembros que estando en plena comunión y se casaren con persona inconversa, deberán ser juzgados por los Pastores.</p>
            </div>
            
            <div class="item">
              <h1><span>Sanidad Divina</span></h1>
              <img src="<?=App::media('/doctrinas/13-sanidad-divina.jpg')?>" alt="Sanidad Divina" title="Sanidad Divina" />
              <p>Creemos que Dios tiene poder para sanar todas nuestras dolencias físicas, si así es su voluntad, y que la sanidad divina es un resultado del sacrificio de Cristo, pues él llevó nuestras enfermedades y sufrió nuestros dolores ( Isaías 53:4).</p>
              <p>La sanidad del cuerpo se efectúa por una combinación de la fe del creyente y el poder del nombre de Jesucristo que se invoca sobre el enfermo. El Señor Jesucristo prometió que los que creyeran en su nombre pondrían las manos sobre los enfermos y estos sanarían ( Marcos 16:18 ).</p>
              <p>Los enfermos deben ser ungidos con aceite en el nombre de Jesucristo por ministros ordenados para que el Señor cumpla sus promesas ( Salmos 103:1-4;  Lucas 9:1-3; Juan 14:13; 1 Corintios 12:9; Santiago 5:14-16 ).</p>
              <p>Creemos que la sanidad divina se obtiene por la fe, y que en caso de que algún hermano tenga necesidad de someterse a los cuidados y ministraciones de la ciencia médica, los demás no deben criticarlo, sino considerarse a sí mismos y guardarse de encontrar condenación con lo que ellos mismos aprueban ( Romanos 14:22).</p>
              <p>Recomendamos que los miembros y ministros se abstengan de lanzar críticas indebidas a la ciencia médica, cuyos adelantos nadie puede negar, y que se originan en la habilidad que Dios ha dado a los hombres para ir descubriendo los secretos del funcionamiento del organismo humano. Al mismo tiempo, los exhortamos a que no se opongan a las campañas de higiene, vacunación y limpieza que sean iniciadas por el gobierno, sino que, por el contrario, colaboren decididamente en los lugares donde sea posible.</p>
            </div>
            
            <div class="item">
              <h1><span>Santidad</span></h1>
              <img src="<?=App::media('/doctrinas/14-santidad.jpg')?>" alt="Santidad" title="Santidad" />
              <p>Creemos que todos los miembros del cuerpo de Cristo deben ser santos, es decir, apartados del pecado y consagrados al servicio de Dios. Por esta razón deben abstenerse de toda clase de prácticas, diversiones e inmundicias de carne y del espíritu ( Levítico 19:2; 2 Corintios 7:1; Efesios 5:26, 27; 1 Tesalonicenses 4:3, 4; 2 Timoteo 2:21;  Hebreos 12:14; 1 Pedro 1:16).</p>
              <p>Sin embargo, en la práctica de la santidad, creemos que debe evitarse toda clase de extremismos, ascetismos y privaciones que tienen cierta reputación de sabiduría, en culto voluntario y humildad y en duro trato (te la carne, la cual es sombra de lo porvenir, más el cuerpo es de Cristo ( Colosenses 2:17,23 ). En lo que respecta a alimentos, sabiendo que "todo lo que Dios creó es bueno y nada hay que desechar tomándolo con acción de gracias" ( 1 Timoteo 4:4 ).</p>
            </div>
            
            <div class="item">
              <h1><span>Pecado de Muerte</span></h1>
              <img src="<?=App::media('/doctrinas/15-pecado-de-muerte.jpg')?>" alt="Pecado de Muerte" title="Pecado de Muerte" />
              <p>Creemos, a la luz de la Palabra de Dios, que hay pecado de muerte y que si este es cometido en los términos que expresa la misma Biblia, se pierde el derecho a la salvación ( Mateo 12:31,32; Romanos 6:23; Hebreos 10:26,27; 1 Juan 5:16,17 ).</p>
              <p>Por tanto, recomendamos que todos los fieles se abstengan de dar oído a doctrinas en que se promete seguridad eterna al cristiano sin importar su conducta, y la idea de que "una vez salvo, siempre salvo", pues la Biblia enseña que es posible ser reprobado y se necesita ser fiel hasta el fin ( Romanos 2:6-10; 1 Corintios 9:26,27 ).</p>
            </div>
            
            <div class="item">
              <h1><span>Resurreción</span></h1>
              <img src="<?=App::media('/doctrinas/16-resurreccion.jpg')?>" alt="Resurreción" title="Resurreción" />
              <p>Creemos que habrá una resurrección literal de los muertos en el Señor, en la cual serán revestirlos con un cuerpo glorificado y espiritual, con el cual vivirán para siempre en la presencia del Señor ( Job 19:25-27; Salmos17:15; Juan 5:29; Hechos 24:15; 1 Corintios 15:35-54; 1 Tesalonicenses 4:16 ).</p>
              <p>Los cristianos que estén en pie en el momento en que el Señor recoja a su Iglesia serán igualmente transformados y así irán a estar con el Señor por siempre en gloria ( 1 Corintios 15:51,52; 1 Tesalonicenses 4:18 ).</p>
              <p>Creemos también, que habrá resurrección de injustos, pero estos despertarán del sueño de la tumba para ser juzgados y oír la sentencia que los hará herederos del fuego eterno ( Daniel 12:2; Mateo 25:26; Marcos 9:44; Juan 5:29; Apocalipsis 20:12-15 ).</p>
            </div>
            
            <div class="item">
              <h1><span>Recogimiento</span></h1>
              <img src="<?=App::media('/doctrinas/17-recogimiento.jpg')?>" alt="Recogimiento" title="Recogimiento" />
              <p>Creemos que la Iglesia compuesta de los muertos en el Señor y los fieles que estén sobre la tierra en el momento del rapto, será levantada para ir a encontrar a su Señor en los aires y participar en las bodas del Cordero.</p>
              <p>Después vendrá con el Señor a la tierra para hacer el juicio de las naciones y reinar con Cristo mil años. Este período será precedido por la gran tribulación y la batalla del Armagedón, a la cual dará fin el Señor cuando descienda sobre el Monte de los Olivos con todos sus santos ( Isaías 66:17-25; Daniel 7:27; Miqueas 4:1-3; Zacarías 14:1-6; Mateo 5:5; Romanos 11:25-27; 1 Corintios 15:51-54; Filipenses 3:20,2l; 1 Tesalonicenses 4:13-17; Apocalipsis 20:1-5 ).</p>
            </div>
            
            <div class="item">
              <h1><span>Juicio Final</span></h1>
              <img src="<?=App::media('/doctrinas/18-juicio-final.jpg')?>" alt="Juicio Final" title="Juicio Final" />
              <p>Creemos que hay un juicio preparado en el cual participarán todos los hombres que hayan muerto sin Cristo y los que estén sobre la tierra en el tiempo de su verificación.</p>
              <p>Este juicio se efectuará al final del milenio y también se conoce con el nombre de Juicio del Trono Blanco. La Iglesia no será juzgada en esta ocasión, sino que ella misma intervendrá en el juicio que se haga a todos los hombres de acuerdo con lo que está escrito en los libros que Dios tiene.</p>
            </div>


          </div>
        </div>

      </div>

      <div class="span4">
        <aside>
          <div class="bs-docs-sidebar navigator">
            <h1><span>18 Puntos Doctrinales</span></h1>
            <ul class="nav nav-list navigator">
              <li class="active"><a data-slide-to="0" ><span class="icon-chevron-right"></span> Dios</a></li>
              <li><a data-slide-to="1" ><span class="icon-chevron-right"></span> Jesucristo</a></li>
              <li><a data-slide-to="2" ><span class="icon-chevron-right"></span> Espíritu Santo</a></li>
              <li><a data-slide-to="3" ><span class="icon-chevron-right"></span> Resurreción de Jesucristo</a></li>
              <li><a data-slide-to="4" ><span class="icon-chevron-right"></span> Iglesia</a></li>
              <li><a data-slide-to="5" ><span class="icon-chevron-right"></span> Iglesia y Estado</a></li>
              <li><a data-slide-to="6" ><span class="icon-chevron-right"></span> Servicio Militar</a></li>
              <li><a data-slide-to="7" ><span class="icon-chevron-right"></span> Sistema Economico</a></li>
              <li><a data-slide-to="8" ><span class="icon-chevron-right"></span> Cuerpo Ministerial</a></li>
              <li><a data-slide-to="9" ><span class="icon-chevron-right"></span> Bautismo</a></li>
              <li><a data-slide-to="10" ><span class="icon-chevron-right"></span> Comunión</a></li>
              <li><a data-slide-to="11" ><span class="icon-chevron-right"></span> Matrimonio</a></li>
              <li><a data-slide-to="12" ><span class="icon-chevron-right"></span> Sanidad Divina</a></li>
              <li><a data-slide-to="13" ><span class="icon-chevron-right"></span> Santidad</a></li>
              <li><a data-slide-to="14" ><span class="icon-chevron-right"></span> Pecado de Muerte</a></li>
              <li><a data-slide-to="15" ><span class="icon-chevron-right"></span> Resurreción</a></li>
              <li><a data-slide-to="16" ><span class="icon-chevron-right"></span> Recogimiento</a></li>
              <li><a data-slide-to="17" ><span class="icon-chevron-right"></span> Juicio Final</a></li>
            </ul>
          </div>

          <?=App::module('Addons')->renderBlock("site/index","social-networks", array("style" => "big") )?>
        </aside>
      </div>

    </div>

</div>