
<div role="main" class="container-fluid main">

    <div class="row-fluid fit-to-design">
      <div class="span8 sitemap">
        <?=$this->article['article']?>
      </div>

      <div class="span4">
        no se que onda este pasando pero no quiere quedar estono se que onda este pasando pero no quiere quedar estono se que onda este pasando pero no quiere quedar esto
      </div>

    </div>

</div>