
  <?php if( ! empty( $this->events ) ): ?>
  <?php $separator = "/"; ?>

    <div class="panel panel-default no-round addon-social">
      <div class="panel-heading no-round">
        <h3 class="panel-title"><span class="icon-star-empty"></span> <?=App::xlat('business_social')?></h3>
      </div>
      <div class="panel-body">
        <?php foreach( $this->events AS $social ): ?>

          <?php $path = '/social'. App::module('Core')->getModel('Dates')->toDate(12, $social['created'] ) . $social['id'] . '/gallery/social.jpg'; ?>
            <figure>
              <?php if( file_exists( WP.DS.'media'.$path ) ): ?>
                <?php $img = App::media( $path ); ?>
              <?php else: ?>
                <?php $img = App::media('/images/article-promotion.jpg'); ?>
              <?php endif; ?>
              <a class="sGal_<?=$social['id']?>_btn">
                <img class="img-responsive" src="<?=$img?>" alt="<?=$social['description']?>" title="<?=$social['description']?>" />
              </a>
              <figcaption>
                <time><span class="icon-calendar"></span> <?=App::module('Core')->getModel('Dates')->toDate(7, $social['event'] )?></time><br />
                <?=$social['description']?>
              </figcaption>
            </figure>
            <?=App::module('Addons')->renderBlock("social/index","hidden-images", array('id' => $social['id'], 'created' => $social['created'] ))?>

        <?php endforeach;?>
      </div>
    </div>
  <?php endif;?>

<?php
/*
Array
(
  [0] => Array
    (
      [id] => 20
      [business] => toys@toys.com
      [business_name] => Toys de mazatlan  
      [username] => 
      [description] => Mi cumpleaños numero 36, si Dios quiere
      [event] => 2013-08-12 17:21:43
      [created] => 2013-07-31 16:13:51
      [city] => mazatlan
      [folder] => 1375308204
      [status] => enabled
    )
*/
?>