
  <div class="container">
    <article class="row">

      <section class="three fifths right-one padded no-top-pad">
          <?=App::module('Addons')->renderBlock("site/index","top-menu")?>


           <?php if( ! empty($this->events['items']) ): ?>

             <?php foreach($this->events['items'] AS $event): ?>
    
                <article class="list">
                  <?php if( file_exists( WP.DS.'media'.DS.$event['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
                    <a href="<?=App::base( App::xlat( $event['type'].'_singular' ) ."/". $event['seo']  )?>">
                      <img src="<?=App::media( $event['folder']."/gallery/article.jpg" )?>" alt="<?=$event['title']?>" title="<?=$event['title']?>" />
                    </a>
                  <?php else: ?>
                    <a href="<?=App::base( App::xlat( $event['type'].'_singular' ) ."/". $event['seo']  )?>">
                      <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$event['title']?>" title="<?=$event['title']?>" />
                    </a>
                  <?php endif;?>
    
                  <p class="span pull-right info">
                    <span class="icon-calendar"></span> <?=App::locale()->toDate( $event['publicated'] ,'long')?> |
                    <span class="icon-user"></span> <?=$event['author']?> 
                    <?php if( App::getEnvironment()!=='devel' ):?>
                      | <span class="icon-comments"></span> <fb:comments-count href="<?=App::base( App::xlat('eventos_singular').'/'. $event['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                    <?php endif;?>
                  </p>
                  <h2><a href="<?=App::base( App::xlat( $event['type'].'_singular' ) ."/". $event['seo']  )?>"><?=$event['title']?></a></h2>
                  <p><?=strip_tags($event['article'])?></p>
                  <p><a class="btn-info btn-mini pull-right" href="<?=App::base( App::xlat('eventos_singular').'/'. $event['seo'] )?>"><?=App::xlat('read_more')?></a></p>
                </article>
    
             <?php endforeach; ?>
             <?= empty($this->events['pagination_html']) ? '' : $this->events['pagination_html'];?>
    
           <?php else:?>
             <div class="well"> <?=App::xlat('no_data_found')?> [list#37] </div>
           <?php endif;?>



      </section>
      <aside class="one fifth left-three desktop-only">
        <?=App::module('Addons')->renderBlock("site/index","logo")?>
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
      </aside>
      <aside class="one fifth">
        <?=App::module('Addons')->renderBlock("site/index","promotions")?>
      </aside>
    </article>

  </div>
