
<div role="main" class="container main">

  <div class="row fit-to-design">
    <div class="span3">
        <a href="<?=App::base('')?>">
          <img class="logo" src="<?=App::media('/images/places-to-go.png')?>" />
        </a>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>

    <div class="span7">
        <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
        <?php if( file_exists( $file ) ): ?>
          <img src="<?=App::media( $this->event['folder']."gallery/article.jpg" )?>" alt="<?=$this->event['title']?>" title="<?=$this->event['title']?>" class="article" />
        <?php else: ?>
          <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$this->event['title']?>" title="<?=$this->event['title']?>" class="article" />
        <?php endif;?>

        <?=App::module('Articles')->renderBlock("addons/index","below-image", array('id' => $this->event['article_id'], 'created'=> $this->event['created'], 'folders'=>$this->folders ))?>
        <?=App::module('Addons')->renderBlock("facebook/index","like-and-recommend-content", array('document_route' => App::xlat('eventos_singular'), 'seo' => $this->event['seo'] ))?>

        <div class="reading">
          <h1> <?=$this->event['title']?> </h1>

          <span class="span pull-right info">
            <span class="icon-calendar icon-white"></span> <?=App::locale()->toDate( $this->event['publicated'] ,'long')?> |
            <span class="icon-user icon-white"></span> <?=$this->event['author']?> 
            <?php if( App::getEnvironment()!=='devel' ):?>
              | <span class="icon-comments icon-white"></span> <fb:comments-count href="<?=App::base( App::xlat('eventos_singular').'/'. $this->event['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
            <?php endif;?>
          </span>

          <?=$this->event['article']?>
          <?=App::module('Addons')->renderBlock("facebook/index","comments", array('document_route' => App::xlat('eventos_singular'), 'seo' => $this->event['seo'] ))?>
        </div>

    </div>

    <div class="span2">
      <?=App::module('Addons')->renderBlock("site/index","banner-right")?>
    </div>

  </div>

</div>

<?php 
/*
Array
(
    [id] => 339
    [article_id] => 196
    [title] => Escuchando musica cristiana
    [seo] => escuchando-musica-cristiana
    [article] => Contenido completo del articulo aqui
    [email] => 
    [phone] => 
    [address] => 
    [type_id] => 69
    [type] => articulos
    [type_name] => Articulos
    [created] => 2013-01-19 12:38:44
    [publicated] => 2013-01-19
    [event_date] => 
    [stop_publication] => 
    [username] => robe@gmail.com
    [author] => Roberto Mejia Bañuelos
    [language] => es
    [written] => 1
    [folder] => /articles/2013/01/196/
    [promote] => enabled
    [mobile] => enabled
    [addon] => enabled
    [status] => enabled
)
 */

?>