
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections events">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>


        <div class="container">
          <div class="col-lg-8 col-sm-7 sections events">

            <ol class="breadcrumb">
              <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
              <li class="active"> <span class="icon-music"></span> <?=App::xlat('event_list')?> </li>
            </ol>

            <h3><?=App::xlat('event_list')?></h3>

            <?php if( ! empty($this->events['items']) ): ?>
              <?php $dates = App::module('Core')->getModel('Dates'); ?>

              <?php foreach($this->events['items'] AS $event): ?>

                <figure>
                  <a href="<?=App::www( App::xlat('eventos_singular') . '/' . $event['seo'] )?>">
                    <?php if( file_exists( WP.DS.'media'.DS.$event['folder'].DS.'gallery'.DS.'category.jpg' ) ): ?>
                      <?php $img = App::media( $event['folder']."/gallery/category.jpg" ); ?>
                    <?php else: ?>
                      <?php $img = App::media('/images/missing-category.png'); ?>
                    <?php endif; ?>
                    <img class="img-responsive" src="<?=$img?>" alt="<?=App::xlat($event['title'])?>" />
                  </a>
                  <figcaption>
                    <h1><?=$event['address']?></h1>
                    <time><?=$dates->toDate(13,$event['created'])?></time><br />
                    <p><?=trim(substr( strip_tags($event['article']) , 0, 80)); ?>...</p>
                  </figcaption>
                </figure>

              <?php endforeach; ?>

               <?=$this->events['pagination_html']?>

            <?php else:?>
              <p>Nada que mostrar</p>
            <?php endif;?>

          </div>
          <div class="col-lg-4 col-sm-5 sections events">
            <?=App::module('Articles')->renderBlock("events/index","events-aside")?>
          </div>
        </div>



    </div>


    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>

<?php 
/*

Array
(
    [id] => 7
    [article_id] => 7
    [title] => Evento probando las horas y minutos
    [seo] => evento-probando-las-horas-y-minutos
    [article] => Descripcion del evento
    [email] => 
    [phone] => 
    [address] => Preparatoria Ruben Jaramillo
    [type_id] => 70
    [type] => eventos
    [type_name] => Eventos
    [created] => 2013-08-04 02:54:44
    [publicated] => 2013-08-04
    [event_date] => 2013-08-23
    [event_hours] => 10:00
    [stop_publication] => 2013-08-24
    [username] => robe@gmail.com
    [author] => Places to go! 
    [language] => es
    [written] => 1
    [folder] => /events/2013/08/7/
    [promote] => enabled
    [mobile] => enabled
    [addon] => enabled
    [status] => enabled
)

 */
?>