
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-envelope"></span> <?=App::xlat('about_us')?> </li>
      </ol>

      <h3><?=App::xlat('about_us')?></h3>

           <?php if( ! empty($this->events['items']) ): ?>

             <?php foreach($this->events['items'] AS $event): ?>
                <article class="event_list">
                  <h3> <a class="topic" href="<?=App::www( App::xlat( $event['type'].'_singular' ) ."/". $event['seo']  )?>"><?=$event['title']?></a> </h3>

                  <?php if( file_exists( WP.DS.'media'.DS.$event['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
                    <a href="<?=App::www( App::xlat( $event['type'].'_singular' ) ."/". $event['seo']  )?>">
                      <img src="<?=App::media( $event['folder']."/gallery/article.jpg" )?>" alt="<?=$event['title']?>" title="<?=$event['title']?>" />
                    </a>
                  <?php else: ?>
                    <a href="<?=App::www( App::xlat( $event['type'].'_singular' ) ."/". $event['seo']  )?>">
                      <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$event['title']?>" title="<?=$event['title']?>" />
                    </a>
                  <?php endif;?>

                  <div class="event_list_info">
                    <span class="icon-home gray"></span> <?=$event['address']?>
                    <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> <span class="icon-calendar gray"></span> <?=App::locale()->toDate( $event['publicated'] ,'long')?>
                    <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> <span class="icon-time gray"></span> <?=$event['event_hours']?>
                   <?php if( App::getEnvironment()!=='devel' ):?>
                      <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> <span class="icon-comments gray"></span> <fb:comments-count href="<?=App::www( App::xlat('eventos_singular').'/'. $event['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                    <?php endif;?>
                  </div>
                  <?=$event['article']?>
                </article>
    
             <?php endforeach; ?>
             <?= empty($this->events['pagination_html']) ? '' : $this->events['pagination_html'];?>
    
           <?php else:?>
             <div class="well"> <?=App::xlat('no_data_found')?> [list#37] </div>
           <?php endif;?>

    </div>


    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>
