
  <div class="container">
    <article class="row">

      <section class="three fifths right-one padded no-top-pad">

          <?=App::module('Addons')->renderBlock("site/index","top-menu")?>

          <article class="read-new">
            <h3> <?=$this->event['title']?> </h3>

            <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
            <?php if( file_exists( $file ) ): ?>
              <img src="<?=App::media( $this->event['folder']."gallery/article.jpg" )?>" alt="<?=$this->event['title']?>" title="<?=$this->event['title']?>" class="article" />
            <?php else: ?>
              <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$this->event['title']?>" title="<?=$this->event['title']?>" class="article" />
            <?php endif;?>
              <div class="event_info">
                <span class="icon-home gray"></span> <?=$this->event['address']?>
                <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> <span class="icon-calendar gray"></span> <?=App::locale()->toDate( $this->event['publicated'] ,'long')?>
                <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> <span class="icon-time gray"></span> <?=$this->event['hours'].':'.$this->event['min']?>
                <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> <span class="icon-user gray"></span> <?=$this->event['author']?>
                <?php if( App::getEnvironment()!=='devel' ):?>
                  <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span>  <span class="icon-comments  gray"></span> <fb:comments-count href="<?=App::base( App::xlat('eventos_singular').'/'. $this->event['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                <?php endif;?>
              </div>

              <?=$this->event['article']?>

              <h3><span class="icon-question-sign"></span> <?=App::xlat('event_where_when_time')?></h3>
              <p>
                <span class="icon-home"></span> <?=$this->event['address']?> <br />
                <span class="icon-calendar"></span> <?=App::locale()->toDate( $this->event['publicated'] ,'long')?> <br />
                <span class="icon-time"></span> <?=$this->event['hours'].':'.$this->event['min']?>
              </p>
              <?=App::module('Articles')->renderBlock("addons/index","article-addons", array('id' => $this->event['article_id'], 'created'=> $this->event['created'], 'folders'=>$this->folders ))?>
          </article>

      </section>
      <aside class="one fifth left-three desktop-only">
        <?=App::module('Addons')->renderBlock("site/index","logo")?>
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
      </aside>
      <aside class="one fifth">
        <?=App::module('Addons')->renderBlock("site/index","promotions")?>
      </aside>
    </article>

  </div>


<?php 
/*
Array
(
    [id] => 339
    [article_id] => 196
    [title] => Escuchando musica cristiana
    [seo] => escuchando-musica-cristiana
    [article] => Contenido completo del articulo aqui
    [email] => 
    [phone] => 
    [address] => 
    [type_id] => 69
    [type] => articulos
    [type_name] => Articulos
    [created] => 2013-01-19 12:38:44
    [publicated] => 2013-01-19
    [event_date] => 
    [stop_publication] => 
    [username] => robe@gmail.com
    [author] => Roberto Mejia Bañuelos
    [language] => es
    [written] => 1
    [folder] => /articles/2013/01/196/
    [promote] => enabled
    [mobile] => enabled
    [addon] => enabled
    [status] => enabled
)
 */

?>