
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections read-event">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li> <span class="icon-music"></span> <a href="<?=App::www( App::xlat('eventos') )?>"><?=App::xlat('event_list')?></a></li>
        <li class="active"> <span class="icon-music"></span> <?=$this->event['title']?> </li>
      </ol>

      <?php $dates = App::module('Core')->getModel('Dates'); ?>

      <h3> <?=$this->event['title']?> </h3>

      <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
      <figure class="round-bottom" >
      <?php if( file_exists( WP.DS.'media'.DS.$this->event['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
        <?php $img = App::media( $this->event['folder']."/gallery/article.jpg" ); ?>
      <?php else: ?>
        <?php $img = App::media('/images/article-preview.png'); ?>
      <?php endif; ?>
      <img class="img-responsive" src="<?=$img?>" alt="<?=$this->event['title']?> title="<?=$this->event['title']?>" />

        <figcaption>
          <span class="icon-home gray"></span> <?=$this->event['address']?>
          <span class="hide-on-mobile">|</span> <span class="icon-calendar gray"></span> <?=App::locale()->toDate( $this->event['publicated'] ,'long')?>
          <span class="hide-on-mobile">|</span> <span class="icon-time gray"></span> <?=$this->event['hours'].':'.$this->event['min']?>
          <span class="hide-on-mobile">|</span> <span class="icon-user gray"></span> <?=$this->event['author']?>
          <?php if( App::getEnvironment()!=='devel' ):?>
            <span class="hide-on-mobile">|</span>  <span class="icon-comments  gray"></span> <fb:comments-count href="<?=App::base( App::xlat('eventos_singular').'/'. $this->event['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
          <?php endif;?>
        </figcaption>

      </figure>

        <?=$this->event['article']?>

        <?=App::module('Articles')->renderBlock("addons/index","article-addons", array('id' => $this->event['article_id'], 'created'=> $this->event['created'], 'folders'=>$this->folders ))?>

    </div>


    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>

<?php 
/*
Array
(
    [id] => 339
    [article_id] => 196
    [title] => Escuchando musica cristiana
    [seo] => escuchando-musica-cristiana
    [article] => Contenido completo del articulo aqui
    [email] => 
    [phone] => 
    [address] => 
    [type_id] => 69
    [type] => articulos
    [type_name] => Articulos
    [created] => 2013-01-19 12:38:44
    [publicated] => 2013-01-19
    [event_date] => 
    [stop_publication] => 
    [username] => robe@gmail.com
    [author] => Roberto Mejia Bañuelos
    [language] => es
    [written] => 1
    [folder] => /articles/2013/01/196/
    [promote] => enabled
    [mobile] => enabled
    [addon] => enabled
    [status] => enabled
)
 */

?>