
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>



    <div class="col-lg-6 col-sm-6 sections read-new">
      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li> <span class="icon-question-sign"></span> <a href="<?=App::www('mazatlan/municipio/mazatlan')?>"><?=$this->town['name']?></a></li>
        <li class="active"> <span class="icon-envelope"></span> <?=App::xlat($this->town['section'])?> </li>
      </ol>

      <h3> <?=$this->town['name']?> :: <?=App::xlat($this->town['section'])?> </h3>
      <?=App::module('Addons')->renderBlock("site/twitterbootstrap","image-slider", array( 'target'=>'#city-section', 'folder'=> '/cities'.$this->town['folder'].'gallery/', 'path'=> WP.'/media' ))?>
      <?=$this->town['article']?>
    </div>

    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Articles')->renderBlock("events/index","events-aside",array('limit'=>3))?>
      <?=App::module('Articles')->renderBlock("index","latest-aside",array('limit'=>3))?>
      <?=App::module('Addons')->renderBlock("site/index","cloud-tag",array('chars'=>25))?>
    </div>
    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>

<?php 
/*
Array
(
    [id] => 34
    [town] => cuan-grande-es-dios
    [section] => municipios
    [article] => Y todos le veran.....cuan grannnnnndeeee es Dios!
    [status] => enabled
    [created] => 2013-07-01 20:37:50
    [author] => pue17@gmail.com
    [city] => mazatlan
    [name] => Cuan grande es Dios
    [folder] => /mazatlan/towns/cuan-grande-es-dios/
)
 */

?>
?>