
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections about-us">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-envelope"></span> <?=$this->town['name']?> :: <?=App::xlat($this->town['section'])?> </li>
      </ol>

      <h3><?=$this->town['name']?> :: <?=App::xlat($this->town['section'])?></h3>

      <article class="read-new">
        <?=App::module('Addons')->renderBlock("site/index","town-gallery", array( 'town'=>$this->town['town'], 'folder'=>$this->town['folder'], 'city'=>$this->town['city'] ))?>
        <?=$this->town['article']?>
      </article>

    </div>


    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>

<?php 
/*
Array
(
    [id] => 34
    [town] => cuan-grande-es-dios
    [section] => municipios
    [article] => Y todos le veran.....cuan grannnnnndeeee es Dios!
    [status] => enabled
    [created] => 2013-07-01 20:37:50
    [author] => pue17@gmail.com
    [city] => mazatlan
    [name] => Cuan grande es Dios
    [folder] => /mazatlan/towns/cuan-grande-es-dios/
)
 */
?>