<?php 
  $town_session = App::module('Core')->getModel('Namespace')->get( 'town' ); 
  $user_session = App::module('Core')->getModel('Namespace')->get( 'user' );
?>

  <!-- tabs -->
  <div id="add-town-tabs">

    <ul class="tabs_title">
      <li><a href="#tabs-1"><?=App::xlat('article_tab_title_basic')?></a></li>
      <li><a href="#tabs-2"><?=App::xlat('article_tab_title_more_info')?></a></li>
      <li><a href="#tabs-4"><?=App::xlat('article_tab_title_addons')?></a></li>
    </ul>

    <div id="tabs-1">
      <form id="add-town">
        <?=$this->basic_data->article_id?>
        <?=$this->basic_data->type?>

          <div class="left-fieldset">

            <fieldset class="group access" id="access">
              <legend><?=App::xlat('fieldset_title_password_change')?></legend>

                <dl class="element field-pass type-text">
                  <dt class="label"><label for="pass"><?=App::xlat('new_password')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->pass?>
                  </dd>
                  <dd class="hint"><?=App::xlat('FORM_password_desc')?></dd>
                </dl>

                <dl class="element field-confirmation type-text">
                  <dt class="label"><label for="confirmation"><?=App::xlat('FORM_confirmation')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->confirmation?>
                  </dd>
                  <dd class="hint"><?=App::xlat('FORM_confirmation_desc')?></dd>
                </dl>

            </fieldset>

            <fieldset class="group info" id="info">
              <legend><?=App::xlat('basic_info')?></legend>

                <dl class="element field-name type-text">
                  <dt class="label"><label for="name"><?=App::xlat('town_name')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->name?>
                  </dd>
                </dl>

                <dl class="element field-seo type-text">
                  <dt class="label"><label for="seo"><?=App::xlat('town_seo')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->seo?>
                  </dd>
                  <dd class="hint"><?=App::xlat('FORM_seo_description')?></dd>
                </dl>

                <dl class="element field-tags type-tags">
                  <dt class="label"><label for="tags"><?=App::xlat('FORM_tags_category_title')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->tags?>
                  </dd>
                </dl>

                <dl class="element field-username type-text">
                  <dt class="label"><label for="username"><?=App::xlat('FORM_email')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->username?>
                  </dd>
                </dl>

                <dl class="element field-city type-text">
                  <dt class="label"><label for="city"><?=App::xlat('FORM_city')?></label></dt>
                  <dd class="field">
                    <?=$this->basic_data->city?>
                  </dd>
                </dl>

            </fieldset>

          </div>      

          <div class="right-fieldset">

                <fieldset id="f_main_pix" class="no-margin">
                  <legend><?=App::xlat('ARTICLE_FIELDSET_main_picture_title')?></legend>
                    <p><?=App::xlat('ARTICLE_FIELDSET_main_picture_desc')?></p>
                    <div id="uploader_f_main_pix">
                      <div id="main-pix-filelist"></div>
                      <a id="main-pix-pick" href="#">[ <?=App::xlat('ARTICLE_main_picture_btn_select')?> ]</a>
                      <a id="main-pix-upload" href="#">[ <?=App::xlat('ARTICLE_main_picture_btn_upload')?> ]</a>
                      <a id="mainpix_preview"  href="<?=App::base('/towns/main-pix-preview/')?>">[ <?=App::xlat('ARTICLE_main_picture_btn_preview')?> ]</a>
                    </div>
                </fieldset>
                <fieldset id="f_gallery">
                  <legend><?=App::xlat('ARTICLE_FIELDSET_gallery_title')?></legend>
                    <div id="uploader_f_gallery">
                      <p><?=App::xlat('ARTICLE_FIELDSET_plupload_browser_not_supported')?></p>
                    </div>
                </fieldset>
                <fieldset id="gallery_uploaded">
                  <legend><?=App::xlat('ARTICLE_FIELDSET_gallery_uploaded_images')?></legend>
                    <span class="gp_response"></span>
                    <div class="uploaded_images">
                      <?php if( ! empty( $town_session->town['article_id'] ) ): ?>
                        <?=App::module('Addons')->renderBlock("town","gallery");?>
                      <?php endif;?>
                    </div>
                </fieldset>

          </div>

      </form>

    </div>

    <div id="tabs-2">
      <form id="add-section">
        <fieldset id="town_sections">
          <legend><?=App::xlat('town_section_title')?></legend>
            <div id="daOption">
              <?=App::module('Addons')->renderBlock("town","sections");?>
            </div>
            <div id="daSection">
              <div class="instructions"><?=App::xlat('town_section_description')?></div>

                <div id="accordion">
                  <h3><?=App::xlat('FIELDSET_town_description')?></h3>
                  <div class="panel">
                    <fieldset id="section_info">
                      <legend></legend>
                      <div class="daSectionCkeditor"></div>
                    </fieldset>
                  </div>
                  <h3><?=App::xlat('ARTICLE_FIELDSET_gallery_title')?></h3>
                  <div class="panel">

                    <fieldset id="f_section_gallery">
                      <legend><?=App::xlat('ARTICLE_FIELDSET_gallery_title')?></legend>
                        <div id="uploader_f_section_gallery">
                          <p><?=App::xlat('ARTICLE_FIELDSET_plupload_browser_not_supported')?></p>
                        </div>
                    </fieldset>
                    <fieldset id="section_gallery_uploaded">
                      <legend><?=App::xlat('ARTICLE_FIELDSET_gallery_uploaded_images')?></legend>
                        <span class="gp_response_section"></span>
                        <div class="section_uploaded_images">
                          <?php if( ! empty( $town_session->town['section'] ) ): ?>
                            <?=App::module('Addons')->renderBlock("town","section-gallery");?>
                          <?php endif;?>
                        </div>
                    </fieldset>

                  </div>
                </div>

            </div>
        </fieldset>
      </form>
    </div>

    <div id="tabs-4">
      <form id="links_rel" enctype="application/x-www-form-urlencoded" action="" method="post">

        <div class="left-fieldset">

          <fieldset id="f_addons_links">
            <legend><?=App::xlat('ARTICLE_FIELDSET_addons_links_title')?></legend>
              <p><?=App::xlat('ARTICLE_FIELDSET_addons_links_desc')?></p>

              <div id="links_ge">
                <div id="links_ge_template" class="grouped-elements">
                  <input id="links_ge_#index#_desc" name="links[#index#][desc]" type="text" class="placeholder desc" placeholder="Descripción del link">
                  <input id="links_ge_#index#_url" name="links[#index#][url]" type="text" class="placeholder url" placeholder="URL de la dirección">
                  <select id="links_ge_#index#_type" name="links[#index#][type]" class="type">
                    <option value="inlink"><?=App::xlat('FIELDSET_links_in')?></option>
                    <option value="exlink"><?=App::xlat('FIELDSET_links_ex')?></option>
                    <option value="video"><?=App::xlat('FIELDSET_links_video')?></option>
                  </select>
                  [<a id="links_ge_remove_current"><?=App::xlat('del_alt')?></a>]
                </div>
                <div id="links_ge_noforms_template" class="error"><?=App::xlat('ARTICLE_FIELDSET_addons_links_empty')?></div>
              </div>

              <div id="links_ge_controls">
                <span class="links_response"></span>
                <span id="links_ge_add" class="ui-button ui-widget ui-state-default ui-button-text-icon-secondary">
                  <span class="ui-button-text"><?=App::xlat('BUTTON_add')?></span>
                  <span class="ui-button-icon-secondary ui-icon ui-icon-plus"></span>
                </span>
                <span id="links_ge_remove_all" class="ui-button ui-widget ui-state-default ui-button-text-icon-secondary">
                  <span class="ui-button-text"><?=App::xlat('BUTTON_delete_all')?></span>
                  <span class="ui-button-icon-secondary ui-icon ui-icon-close"></span>
                </span>
                <span id="save_links_rel" class="ui-button ui-widget ui-state-default ui-button-text-icon-secondary">
                  <span class="ui-button-text"><?=App::xlat('BUTTON_save')?></span>
                  <span class="ui-button-icon-secondary ui-icon ui-icon-disk"></span>
                </span>
              </div>
          </fieldset>
        </div>

        <div class="right-fieldset">
          <fieldset id="f_addons_map">
            <legend><?=App::xlat('ARTICLE_FIELDSET_addons_map_title')?></legend>
              <p><?=App::xlat('ARTICLE_FIELDSET_addons_map_desc')?></p>
              <div id="googleMap" style="width:44.5em;height:31em;"></div>
              <p class="coordinates">Coordenadas: <span id="current_cors"><?=(empty($town_session->town['addons']['map']['reference']))? null: $town_session->town['addons']['map']['reference']?></span></p>

              <span id="del_coordinates" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary">
                <span class="ui-button-text"><?=App::xlat('BUTTON_del_coordinates')?></span>
                <span class="ui-button-icon-secondary ui-icon ui-icon-close"></span>
              </span>
              <span id="save_coordinates" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary">
                <span class="ui-button-text"><?=App::xlat('BUTTON_save')?></span>
                <span class="ui-button-icon-secondary ui-icon ui-icon-disk"></span>
              </span>
              <span class="coord_response"></span>

          </fieldset>
        </div>

      </form>

    </div>


    <div class="button-wrapper">

      <span id="next" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary <?=( empty($town_session->town['article_id'])? null:'hide' ) ?>">
        <span class="ui-button-text"><?=App::xlat('BUTTON_next')?></span>
        <span class="ui-button-icon-secondary ui-icon ui-icon-carat-1-e"></span>
      </span>

      <span id="save" class="<?=( empty($town_session->town['article_id'])? 'hide ':null ) ?>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary">
        <span class="ui-button-text"><?=App::xlat('BUTTON_save')?></span>
        <span class="ui-button-icon-secondary ui-icon ui-icon-check"></span>
      </span>

      <?php if( ! empty( $user_session->user['privileges']['55'] ) ||  ! empty($user_session->user['privileges']['777'])  ) : ?>
        <span id="save_close" class="<?=( empty($town_session->town['article_id'])? 'hide ':null ) ?>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary">
          <span class="ui-button-text"><?=App::xlat('BUTTON_save_close')?></span>
          <span class="ui-button-icon-secondary ui-icon ui-icon-close"></span>
        </span>

        <span id="save_publicate" class="<?=( empty($town_session->town['article_id'])? 'hide ':null ) ?>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary">
          <span class="ui-button-text"><?=App::xlat('BUTTON_save_publicate')?></span>
          <span class="ui-button-icon-secondary ui-icon ui-icon-close"></span>
        </span>
      <?php endif;?>

    </div>

  </div>