
<?php if( ! empty($this->files) ): ?>
  <style>
    img.mpPrev{float: left; padding: 5px; }
    body{ background-color: #000; }
  </style>
  <?php $image_cache_reloader = '?' . date('s'); ?>
  <img class="mpPrev" title="Slider" alt="Slider" src="<?=App::media( $this->files['path'] ."gallery/". $this->files['images']['slider'] . $image_cache_reloader  );?>" />
  <img class="mpPrev" title="Article" alt="Article" src="<?=App::media( $this->files['path'] ."gallery/". $this->files['images']['article'] . $image_cache_reloader );?>" />
  <img class="mpPrev" title="Promote" alt="Promote" src="<?=App::media( $this->files['path'] ."gallery/". $this->files['images']['promote'] . $image_cache_reloader );?>" />
  <img class="mpPrev" title="Listing" alt="Listing" src="<?=App::media( $this->files['path'] ."gallery/". $this->files['images']['listing'] . $image_cache_reloader );?>" />
  <img class="mpPrev" title="Aside" alt="Aside" src="<?=App::media( $this->files['path'] ."gallery/". $this->files['images']['aside'] . $image_cache_reloader );?>" />
  <img class="mpPrev" title="Mobile" alt="Mobile" src="<?=App::media( $this->files['path'] ."gallery/". $this->files['images']['mobile'] . $image_cache_reloader );?>" />
<?php else:?>
  <style>
    .no-main-pix p{ font: lighter 16px arial,sans-serif; padding: 20px; text-align: center;}
    .no-main-pix img{margin: 30px 0 0 360px;}
  </style>
  <div class="no-main-pix">
    <img src="<?=App::media('/images/no-photo.jpg')?>" title="" alt="" />
    <p><?=App::xlat('ARTICLE_main_picture_empty')?></p>
  </div>
<?php endif;?>

<?php 
/*
Array
(
  [path] => /mazatlan/towns/pueblo-ocho/
  [images] => Array
    (
      [slider] => slider.jpg
      [article] => article.jpg
      [promote] => promote.jpg
      [listing] => listing.jpg
      [aside] => aside.jpg
      [mobile] => mobile.jpg
    )
)
 */
?>