
<div class="block rating">
  <h1>
    <?=App::xlat('RATING_block_rate')?>
    <span><?=App::xlat('RATING_block_rating_subtitle')?></span>
  </h1>
  <div class="rate">
    <ul class="star-rating">
      <?php for($star = 1; $star <= 5; $star++): ?>
        <li <?=($this->rating['rating']==$star)? 'class="stars-'.$star.'"' : ''?>>
          <a href="#" class="star-<?=$star?>">
            <?=App::xlat('RATING_' . $star)?>
          </a>
        </li>
      <?php endfor;?>
        <li class="rate-description"></li>
    </ul>
  </div>
</div>

<?php
/*
$this->rating
Array
(
    [id] => 1
    [reference] => 149
    [votes] => 1
    [points] => 4
    [type] => article
    [stat] => 1
    [rating] => 4
)
 */
?>