<?php $type = empty($this->type) ? App::xlat('RATING_block_rate_default_type') : $this->type; ?>

<div class="block rating">
  <h1>
    <?=App::xlat('RATING_block_rate') . $type?>
    <span><?=App::xlat('RATING_block_rating_subtitle')?></span>
  </h1>
  <div id="rate"></div>
  <div id="rate-hint"></div>
  <div id="rate-answer"></div>    
</div>

<?php 
/*
$this->rating
Array
(
    [id] => 1
    [reference] => 149
    [votes] => 1
    [points] => 4
    [type] => article
    [stat] => 1
    [rating] => 4
)
 */
?>