
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>


    <div class="col-lg-8 col-sm-9 sections business-read">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>
      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li> <span class="icon-home"></span> <a href="<?=App::www( App::xlat('empresas') )?>"><?=App::xlat('empresas')?></a></li>
        <li class="active"> <span class="icon-envelope"></span> <?=$this->article['title']?> </li>
      </ol>

      <h3> <?=$this->article['title']?> </h3>

      <article class="read-new">
        <?=App::module('Articles')->renderBlock("addons/index","article-slide-gallery", array('id' => $this->article['article_id'], 'created'=> $this->article['created'], 'folders'=>$this->folders ) )?>
        <?=$this->article['article']?>
        <?=App::module('Addons')->renderBlock("site/index","business-promotions", array('business' => $this->article['username'] ))?>
        <?=App::module('Addons')->renderBlock("social/index","events", array('business' => $this->article['username'] ))?>
        <?=App::module('Articles')->renderBlock("addons/index","article-addons", array('id' => $this->article['article_id'] ))?>
      </article>

    </div>


    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>
