<head>
<meta charset="UTF-8" />
<title><?=isset($this->pageTitle) ? $this->pageTitle:@$this->xd['pageTitle'];?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<meta name="author" content="<?=isset($this->pageAuthor) ? $this->pageAuthor:@$this->xd['pageAuthor'];?>" />
<meta name="copyright" content="<?=isset($this->pageCopyright) ? $this->pageCopyright:@$this->xd['pageCopyright'];?>" />
<meta name="description" content="<?=isset($this->pageDescription) ? $this->pageDescription:@$this->xd['pageDescription'];?>" />
<meta name="keywords" content="<?=isset($this->pageKeywords) ? $this->pageKeywords:@$this->xd['pageKeywords'];?>" />
<meta name="Locality" content="Mazatlan, Mexico" />
<meta name="lang" content="es" />


<!--Links-->
    <link href="<?=App::getDesign()->getRelativeJsPath('/bootstrap/css/bootstrap.min.css')?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeJsPath('/bootstrap/icons/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/errors.css');?>" rel="stylesheet" />


	<?= App::header()->getLinks();?>

	<?=@$this->xd['_block']['links'];?>

<!--Scripts-->
  <!--[if IE]>
    <script src="<?=App::getDesign()->getRelativeJsPath('/html5.js','js');?>"></script>
  <![endif]-->
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-1.9.1.min.js','js');?>" ></script>

    <script src="<?=App::getDesign()->getRelativeJsPath('/bootstrap/js/bootstrap.min.js','js');?>" ></script>

    <script>
      var baseUrl="<?=App::base();?>";
      jQuery(document).ready(function(){
        <?=App::header()->get_jquery_events();?>
      });
    </script>

	<?=App::header()->getScripts();?>

	<?=@$this->xd['_block']['scripts'];?>

	<?=@$this->xd['_block']['add'];?>

	<?=App::header()->getCode();?>

</head>