
<div role="main" class="container article">

    <div class="row fit-to-design">

      <div class="span3">
        <a href="<?=App::base('')?>">
          <img class="logo" src="<?=App::media('/images/places-to-go.png')?>" />
        </a>
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
      </div>

      <div class="span7">

       <?php if( ! empty($this->articles['items']) ): ?>
         <div class="articles">
         <?php foreach($this->articles['items'] AS $article): ?>

            <article class="list">
              <?php if( file_exists( WP.DS.'media'.DS.$article['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
                <a href="<?=App::base( App::xlat( $article['type'].'_singular' ) ."/". $article['seo']  )?>">
                  <img src="<?=App::media( $article['folder']."/gallery/article.jpg" )?>" alt="<?=$article['title']?>" title="<?=$article['title']?>" />
                </a>
              <?php else: ?>
                <a href="<?=App::base( App::xlat( $article['type'].'_singular' ) ."/". $article['seo']  )?>">
                  <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$article['title']?>" title="<?=$article['title']?>" />
                </a>
              <?php endif;?>

              <p class="span pull-right info">
                <span class="icon-calendar icon-white"></span> <?=App::locale()->toDate( $article['publicated'] ,'long')?> |
                <span class="icon-user icon-white"></span> <?=$article['author']?> 
                <?php if( App::getEnvironment()!=='devel' ):?>
                  | <span class="icon-comments icon-white"></span> <fb:comments-count href="<?=App::base( App::xlat('articulos_singular').'/'. $article['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                <?php endif;?>
              </p>
              <h2><a href="<?=App::base( App::xlat( $article['type'].'_singular' ) ."/". $article['seo']  )?>"><?=$article['title']?></a></h2>
              <p><?=strip_tags($article['article'])?></p>
              <a href="<?=App::base( App::xlat('articulos_singular').'/'. $article['seo'] )?>">
                <span class="label label-warning"><?=App::xlat('read_more')?></span>
              </a>
            </article>

         <?php endforeach; ?>
         </div>

         <?= empty($this->articles['pagination_html']) ? '' : $this->articles['pagination_html'];?>

       <?php else:?>

       <?php endif;?>

      </div>

      <div class="span2">
        <?=App::module('Addons')->renderBlock("site/index","banner-right")?>
      </div>

    </div>

</div>