
  <div class="container">
    <article class="row">

      <section class="three fifths right-one padded no-top-pad">

          <?=App::module('Addons')->renderBlock("site/index","top-menu")?>

          <article class="read-new">
            <h3> <?=$this->article['title']?> </h3>
                
            <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
            <?php if( file_exists( $file ) ): ?>
              <img src="<?=App::media( $this->article['folder']."gallery/article.jpg" )?>" alt="<?=$this->article['title']?>" title="<?=$this->article['title']?>" class="article" />
            <?php else: ?>
              <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$this->article['title']?>" title="<?=$this->article['title']?>" class="article" />
            <?php endif;?>
    
            <?=App::module('Articles')->renderBlock("addons/index","below-image", array('id' => $this->article['article_id'], 'created'=> $this->article['created'], 'folders'=>$this->folders ))?>
            

              <span class="info">
                <span class="icon-calendar icon-white"></span> <?=App::locale()->toDate( $this->article['publicated'] ,'long')?> |
                <span class="icon-user icon-white"></span> <?=$this->article['author']?> 
                <?php if( App::getEnvironment()!=='devel' ):?>
                  | <span class="icon-comments icon-white"></span> <fb:comments-count href="<?=App::base( App::xlat('articulos_singular').'/'. $this->article['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                <?php endif;?>
              </span>

              <?=$this->article['article']?>
          </article>
          
          
          
      </section>
      <aside class="one fifth left-three desktop-only">
        <?=App::module('Addons')->renderBlock("site/index","logo")?>
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
      </aside>
      <aside class="one fifth">
        <?=App::module('Addons')->renderBlock("site/index","promotions")?>
      </aside>
    </article>

  </div>