
  <div class="row">

    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'left'))?>
    </div>
    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Addons')->renderBlock("site/index","logo")?>
      <?=App::module('Addons')->renderBlock("site/index","menu")?>
    </div>



    <div class="col-lg-6 col-sm-6 sections news">

      <?=App::module('Addons')->renderBlock("site/index","top-menu",array('padding'=>true))?>

      <ol class="breadcrumb">
        <li> <span class="icon-home"></span> <a href="<?=App::www()?>"><?=App::xlat('home')?></a></li>
        <li class="active"> <span class="icon-file"></span> <?=App::xlat('news_list')?> </li>
      </ol>

      <h3><?=App::xlat('news_list')?></h3>

      <?php if( ! empty($this->articles['items']) ): ?>
        <?php $dates = App::module('Core')->getModel('Dates'); ?>

        <?php foreach($this->articles['items'] AS $article): ?>

          <figure>
            <a href="<?=App::www( App::xlat('articulos_singular') . '/' . $article['seo'] )?>">
              <?php if( file_exists( WP.DS.'media'.DS.$article['folder'].DS.'gallery'.DS.'category.jpg' ) ): ?>
                <?php $img = App::media( $article['folder']."/gallery/category.jpg" ); ?>
              <?php else: ?>
                <?php $img = App::media('/images/missing-category.png'); ?>
              <?php endif; ?>
              <img class="img-responsive" src="<?=$img?>" alt="<?=$article['title']?>" />
            </a>
            <figcaption>
              <time><?=$dates->toDate(13,$article['created'])?></time><br />
              <p>
                <?=trim(substr( strip_tags($article['article']) , 0, 80)); ?>...
                <br /><a class="btn btn-primary btn-xs" href="<?=App::www( App::xlat( 'articulos_singular' ) ."/". $article['seo'] )?>"> <?=App::xlat('read_more')?> <span class="icon-chevron-right"></span> </a>
              </p>
            </figcaption>
          </figure>

        <?php endforeach; ?>

         <?=$this->articles['pagination_html']?>

      <?php else:?>
        <p>Nada que mostrar</p>
      <?php endif;?>

    </div>



    <div class="col-lg-2 col-sm-3 pad-left-right-5">
      <?=App::module('Articles')->renderBlock("events/index","events-aside",array('limit'=>3))?>
      <?=App::module('Articles')->renderBlock("index","latest-aside",array('limit'=>3))?>
      <?=App::module('Addons')->renderBlock("site/index","cloud-tag",array('chars'=>25))?>
    </div>
    <div class="col-lg-1 visible-lg no-padding">
      <?=App::module('Addons')->renderBlock("site/index","cloud",array('direction'=>'right'))?>
    </div>

  </div>