
  <div class="container">
    <article class="row">

      <section class="three fifths right-one padded no-top-pad">

          <?=App::module('Addons')->renderBlock("site/index","top-menu")?>

          <article class="read-new">
            <h3> <?=$this->article['title']?> </h3>

            <?php $file = $full_path = str_replace('\\', DS , $this->folders['gallery'].DS.'article.jpg' ); ?>
            <?php if( file_exists( $file ) ): ?>
              <img src="<?=App::media( $this->article['folder']."gallery/article.jpg" )?>" alt="<?=$this->article['title']?>" title="<?=$this->article['title']?>" class="article" />
            <?php else: ?>
              <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$this->article['title']?>" title="<?=$this->article['title']?>" class="article" />
            <?php endif;?>

              <div class="event_info">
                <span class="icon-calendar  gray"></span> <?=App::locale()->toDate( $this->article['publicated'] ,'long')?> <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span> 
                <span class="icon-user  gray"></span> <?=$this->article['author']?> 
                <?php if( App::getEnvironment()!=='devel' ):?>
                  <br class="hide-on-desktop hide-on-portrait" /> <span class="hide-on-mobile">|</span>  <span class="icon-comments  gray"></span> <fb:comments-count href="<?=App::base( App::xlat('articulos_singular').'/'. $this->article['seo'] )?>"></fb:comments-count> <?=App::xlat('comments')?>
                <?php endif;?>
              </div>

              <?=$this->article['article']?>

              <?=App::module('Articles')->renderBlock("addons/index","article-addons", array('id' => $this->article['article_id'], 'created'=> $this->article['created'], 'folders'=>$this->folders ))?>
          </article>

      </section>
      <aside class="one fifth left-three desktop-only">
        <?=App::module('Addons')->renderBlock("site/index","logo")?>
        <?=App::module('Addons')->renderBlock("site/index","menu")?>
      </aside>
      <aside class="one fifth">
        <?=App::module('Addons')->renderBlock("site/index","promotions")?>
      </aside>
    </article>

  </div>