
<?php if( ! empty($this->addons) ): ?>

  <?php $addon_icon = array('link'=>'link','audio'=>'play','video'=>'facetime-video','files'=>'file-alt ','gallery'=>'picture','map'=>'map-marker');  ?>

  <div class="addons">

    <?php if( array_key_exists('gallery',$this->addons) ): ?>
      <?=App::module('Articles')->renderBlock("addons/index","mini-gallery",array('thumb'=>$this->folders['thumbnails'], 'path'=>$this->folders['url'] ))?>
    <?php endif; ?>

    <?php if( array_key_exists('map',$this->addons) ): ?>

      <div class="panel panel-default no-round addon-map">
        <div class="panel-heading no-round">
          <h3 class="panel-title"><span class="icon-map-marker"></span> <?=App::xlat('addon_map')?></h3>
        </div>
        <div class="panel-body">
          <div id="googleMap" style="width:49em;height:22em;"></div>      
        </div>
      </div>

    <?php endif; ?>

    <?php if( array_key_exists('video',$this->addons) ): ?>
      <div class="panel panel-default no-round addon-video">
        <div class="panel-heading no-round">
          <h3 class="panel-title">
            <span class="icon-play"></span> <?=App::xlat('addon_video')?>
          </h3>
        </div>
        <div class="panel-body">
          <?php foreach($this->addons['video'] AS $child_addon): ?>
            <?=App::module('Addons')->renderBlock("video/index","show-video",array('id'=>$child_addon['reference'],'embed'=>'yes'))?>
          <?php endforeach;?>
        </div>
      </div>

    <?php endif; ?>

    <?php if( array_key_exists('files',$this->addons) ): ?>

      <div class="panel panel-default no-round addon-files">
        <div class="panel-heading no-round">
          <h3 class="panel-title">
            <span class="icon-file"></span> <?=App::xlat('addon_files')?>
          </h3>
        </div>
        <div class="panel-body">
          <ol class="submenu">
            <?php foreach($this->addons['files'] AS $child_addon): ?>
              <li>
                <?=get_addon_link('files',$child_addon['reference'],$child_addon['description'],$child_addon['class'],$child_addon['article_id'],$this->created)?>
              </li>
            <?php endforeach;?>
          </ol>
        </div>
      </div>

    <?php endif; ?>

    <?php if( array_key_exists('link',$this->addons) ): ?>
      <div class="panel panel-default no-round addon-links">
        <div class="panel-heading no-round">
          <h3 class="panel-title">
            <span class="icon-link"></span> <?=App::xlat('addon_links')?>
          </h3>
        </div>
        <div class="panel-body">
          <ol class="submenu">
            <?php foreach($this->addons['link'] AS $child_addon): ?>
              <li>
                <?=get_addon_link('link',$child_addon['reference'],$child_addon['description'],$child_addon['class'],$child_addon['article_id'],$this->created)?>
              </li>
            <?php endforeach;?>
          </ol>
        </div>
      </div>

    <?php endif; ?>

  </div>

<?php endif;?>

<?php 
/*
 * @todo: coderefactor
 */

 function get_addon_link($type=null,$reference=null,$description=null,$class=null,$id=null,$created=null){
   switch($type){
     case 'link':
       return "<a href='$reference' target='".(($class=='exlink')? '_blank':'_self')."' > $description </a>";
       break;
     case 'video':
       return "<a class='video' rel='http://www.youtube.com/v/$reference?rel=0&wmode=transparent&autoplay=1&showinfo=0' > $description </a>";
       break;
     case 'audio':
     case 'files':
       $url=App::base( 'download/'.strtotime($created).'/'.$type.'/'.$id.'/'.$reference );
       return "<a href='$url'> $reference </a>";
       break;
   }

 }

?>

<?php 
/*
wsqClEJpePw

Array
(
    [video] => Array
        (
            [0] => Array
                (
                    [id] => 8
                    [article_id] => 1
                    [type] => video
                    [reference] => wsqClEJpePw
                    [description] => 
                    [class] => video
                    [status] => enabled
                    [desc] => 
                    [url] => http://www.youtube.com/v/wsqClEJpePw
                )

        )

    [files] => Array
        (
            [0] => Array
                (
                    [id] => 2
                    [article_id] => 1
                    [type] => files
                    [reference] => transferencia_de_banorte_a_hsbc.pdf
                    [description] => 
                    [class] => pdf
                    [status] => enabled
                )

        )

    [gallery] => Array
        (
            [id] => 1
            [article_id] => 1
            [type] => gallery
            [reference] => 
            [description] => 
            [class] => 
            [status] => enabled
        )

    [map] => Array
        (
            [id] => 3
            [article_id] => 1
            [type] => map
            [reference] => 23.236338,-106.419153
            [description] => 
            [class] => map
            [status] => enabled
        )

)
 
 */

?>