
<?php if( ! empty($this->addons) ): ?>
  <?php $addon_icon = array('link'=>'link','audio'=>'play','video'=>'facetime-video','files'=>'file-alt ','gallery'=>'picture','map'=>'map-marker');  ?>

  <div class="addons">

        <?php foreach($this->addons AS $key=>$addon): ?>

          <?php if( ! array_key_exists('id', $addon) ): ?>
                <h3><span class="icon-<?=$addon_icon[$key]?>"></span> <?=$key?></h3>
                <ul class="submenu">
                  <?php foreach($addon AS $child_addon): ?>
                    <li>
                      <?=get_addon_link($child_addon['type'],$child_addon['reference'],$child_addon['description'],$child_addon['class'],$child_addon['article_id'],$this->created)?>
                    </li>
                  <?php endforeach;?>
                </ul>

          <?php else: ?>

              <?php if( $key=='map' ): ?>
                <h3><span class="icon-<?=$addon_icon[$key]?>"></span> <?=App::xlat('map_location')?></h3>
                <div id="googleMap" style="width:49em;height:22em;"></div>
              <?php endif; ?>

          <?php endif; ?>
        <?php endforeach;?>

  </div>


<?php endif;?>

<?php 
/*
 * @todo: coderefactor
 */

 function get_addon_link($type=null,$reference=null,$description=null,$class=null,$id=null,$created=null){
   switch($type){
     case 'link':
       return "<a href='$reference' target='".(($class=='exlink')? '_blank':'_self')."' > $description </a>";
       break;
     case 'video':
       return "<a class='video' rel='http://www.youtube.com/v/$reference?rel=0&wmode=transparent&autoplay=1&showinfo=0' > $description </a>";
       break;
     case 'audio':
     case 'files':
     case 'gallery':
       $url=App::base( 'download/'.strtotime($created).'/'.$type.'/'.$id.'/'.$reference );
       return "<a href='$url'> $reference </a>";
       break;
   }

 }

?>

<?php 
/*
wsqClEJpePw

Array
(
    [video] => Array
        (
            [0] => Array
                (
                    [id] => 8
                    [article_id] => 1
                    [type] => video
                    [reference] => wsqClEJpePw
                    [description] => 
                    [class] => video
                    [status] => enabled
                    [desc] => 
                    [url] => http://www.youtube.com/v/wsqClEJpePw
                )

        )

    [files] => Array
        (
            [0] => Array
                (
                    [id] => 2
                    [article_id] => 1
                    [type] => files
                    [reference] => transferencia_de_banorte_a_hsbc.pdf
                    [description] => 
                    [class] => pdf
                    [status] => enabled
                )

        )

    [gallery] => Array
        (
            [id] => 1
            [article_id] => 1
            [type] => gallery
            [reference] => 
            [description] => 
            [class] => 
            [status] => enabled
        )

    [map] => Array
        (
            [id] => 3
            [article_id] => 1
            [type] => map
            [reference] => 23.236338,-106.419153
            [description] => 
            [class] => map
            [status] => enabled
        )

)
 
 */

?>