<nav class="menu gap-top kk" data-label="Places to go: Menu">
  <ul class="nav nav-list kk">
    <li class="nav-header desktop-only"> Mazatlán</li>
    <li class="nav-topic desktop-only">Menu Principal</li>
      <li class="informacion"> <a href="<?=App::base('')?>"> <span class="ptg-informacion"></span> Información</a> </li>

      <li class="hoteles hide-on-desktop"> <a href="<?=App::base('')?>"> <span class="ptg-hoteles"></span> Hoteles</a> </li>
      <li class="cafes hide-on-desktop"> <a href="<?=App::base('')?>"> <span class="ptg-restaurantes"></span> Cafés y Restaurantes</a> </li>
      <li class="antros hide-on-desktop"> <a href="<?=App::base('')?>"> <span class="ptg-antros"></span> Antros &amp; Bares</a> </li>

      <li class="pueblos"> <a href="<?=App::base('')?>"> <span class="ptg-pueblos"></span> Pueblos</a> </li>
      <li class="dondeir"> <a href="<?=App::base('')?>"> <span class="ptg-dondeir"></span> A donde ir ?</a> </li>
      <li class="promos"> <a href="<?=App::base('')?>"> <span class="ptg-promos"></span> Promociones</a> </li>
      <li class="eventos"> <a href="<?=App::base('eventos')?>"> <span class="ptg-eventos"></span> Eventos</a> </li>
      <li class="noticias"> <a href="<?=App::base('articulos')?>"> <span class="ptg-noticias"></span> Noticias</a> </li>
      <li class="agencia"> <a href="<?=App::base('')?>"> <span class="ptg-agencia"></span> Agencia viajes</a> </li>
      <li class="sitios_de_interes"> <a href="<?=App::base('')?>"> <span class="ptg-bienes"></span> Bienes Raices</a> </li>
      <li class="telefonos"> <a href="<?=App::base('')?>"> <span class="ptg-telefonos"></span> Telefonos</a> </li>
      <li class="cines"> <a href="<?=App::base('')?>"> <span class="ptg-registre"></span> Registrarse</a> </li>

    <li class="nav-facebook desktop-only"> <span class="icon-facebook"></span> </li>
      <li class="facebook desktop-only"> <a href="https://www.facebook.com/placestogo.mx">Places To Go</a> </li>

    <li class="nav-twitter desktop-only"> <span class="icon-twitter"></span> </li>
      <li class="twitter desktop-only"> <a>@placestogomx</a> </li>

    <li class="nav-youtube desktop-only"> <span class="icon-play-circle"></span> </li>
      <li class="youtube desktop-only"> <a>placestogomx</a> </li>

    <li class="nav-email desktop-only"> <span class="icon-envelope"></span> </li>
      <li class="email desktop-only"> <a>contacto@placestogo.mx</a> </li>

  </ul>
</nav>