<nav class="left-menu">
  <ul class="nav nav-list">
    <li class="nav-header"> Mazatlán</li>
    <li class="nav-topic">Menu Principal</li>
      <li class="informacion icon"> <a href="<?=App::base('')?>"> <span class="ptg-informacion"></span> Información</a> </li>
      <li class="pueblos icon"> <a href="<?=App::base('')?>"> <span class="ptg-informacion"></span> Pueblos</a> </li>
      <li class="dondeir icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> A donde ir ?</a> </li>
      <li class="eventos icon"> <a href="<?=App::base('eventos')?>"> <span class="icon-chevron-right icon-white"></span> Eventos</a> </li>
      <li class="ninos icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> Promociones</a> </li>
      <li class="pesca icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> Noticias</a> </li>
      <li class="playas icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> Agencia de viajes</a> </li>
      <li class="sitios_de_interes icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> Bienes Raices</a> </li>
      <li class="telefonos icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> Telefonos</a> </li>
      <li class="cines icon"> <a href="<?=App::base('')?>"> <span class="icon-chevron-right icon-white"></span> Registre su negocio</a> </li>

    <li class="nav-facebook"> <span class="icon-facebook"></span> </li>
      <li class="facebook"> <a>Places To Go</a> </li>

    <li class="nav-twitter"> <span class="icon-twitter"></span> </li>
      <li class="twitter"> <a>@placestogomx</a> </li>

    <li class="nav-youtube"> <span class="icon-play-circle"></span> </li>
      <li class="youtube"> <a>placestogomx</a> </li>

    <li class="nav-email"> <span class="icon-envelope"></span> </li>
      <li class="email"> <a>contacto@placestogo.mx</a> </li>

  </ul>
</nav>