
<?php $date = App::module('Core')->getModel('Dates'); ?>

<div class="event-tab block-grey">
  <h1>Eventos</h1>
  <!-- Tabs navigation -->
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#hoy">Hoy</a></li>
    <li><a data-toggle="tab" href="#manana">Mañana</a></li>
    <li><a data-toggle="tab" href="#mes">Del mes</a></li>
  </ul>

  <!-- Tabs content -->
  <div class="tab-content">

    <div id="hoy" class="tab-pane active">
      <?php if( ! empty($this->today) ): ?>
        <?php foreach($this->today AS $today): ?>
          <article class="list">
            <?php if( file_exists( WP.DS.'media'.DS.$today['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
              <a href="<?=App::base( App::xlat( $today['type'].'_singular' ) ."/". $today['seo']  )?>">
                <img src="<?=App::media( $today['folder']."/gallery/aside.jpg" )?>" alt="<?=$today['title']?>" title="<?=$today['title']?>" />
              </a>
            <?php else: ?>
              <a href="<?=App::base( App::xlat( 'eventos_singular' ) ."/". $today['seo']  )?>">
                <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$today['title']?>" title="<?=$today['title']?>" />
              </a>
            <?php endif;?>
  
            <h2><a href="<?=App::base( App::xlat( $today['type'].'_singular' ) ."/". $today['seo']  )?>"><?=$today['title']?></a></h2>
            <p><?=App::locale()->toDate( $today['event_date'] ,'long')?></p>
          </article>
        <?php endforeach; ?>
      <?php else: ?>
        <p> No se han encontrado eventos para hoy </p>
      <?php endif; ?>
    </div>

    <div id="manana" class="tab-pane">
      <?php if( ! empty($this->tomorrow) ): ?>
        <?php foreach($this->tomorrow AS $tomorrow): ?>
          <article class="list">
            <?php if( file_exists( WP.DS.'media'.DS.$tomorrow['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
              <a href="<?=App::base( App::xlat( $tomorrow['type'].'_singular' ) ."/". $tomorrow['seo']  )?>">
                <img src="<?=App::media( $tomorrow['folder']."/gallery/aside.jpg" )?>" alt="<?=$tomorrow['title']?>" title="<?=$tomorrow['title']?>" />
              </a>
            <?php else: ?>
              <a href="<?=App::base( App::xlat( 'eventos_singular' ) ."/". $tomorrow['seo']  )?>">
                <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$tomorrow['title']?>" title="<?=$tomorrow['title']?>" />
              </a>
            <?php endif;?>
  
            <h2><a href="<?=App::base( App::xlat( $tomorrow['type'].'_singular' ) ."/". $tomorrow['seo']  )?>"><?=$tomorrow['title']?></a></h2>
            <p><?=App::locale()->toDate( $tomorrow['event_date'] ,'long')?></p>
          </article>
        <?php endforeach; ?>
      <?php else: ?>
        <p> No se han encontrado eventos para esta fecha </p>
      <?php endif; ?>
    </div>

    <div id="mes" class="tab-pane">
      <?php if( ! empty($this->month) ): ?>
        <?php foreach($this->month AS $month): ?>
          <article class="list">
            <?php if( file_exists( WP.DS.'media'.DS.$month['folder'].DS.'gallery'.DS.'article.jpg' ) ): ?>
              <a href="<?=App::base( App::xlat( $month['type'].'_singular' ) ."/". $month['seo']  )?>">
                <img src="<?=App::media( $month['folder']."/gallery/aside.jpg" )?>" alt="<?=$month['title']?>" title="<?=$month['title']?>" />
              </a>
            <?php else: ?>
              <a href="<?=App::base( App::xlat( 'eventos_singular' ) ."/". $month['seo']  )?>">
                <img src="<?=App::media( '/images/article-preview.jpg' )?>" alt="<?=$month['title']?>" title="<?=$month['title']?>" />
              </a>
            <?php endif;?>
  
            <h2><a href="<?=App::base( App::xlat( $month['type'].'_singular' ) ."/". $month['seo']  )?>"><?=$month['title']?></a></h2>
            <p><?=App::locale()->toDate( $month['event_date'] ,'long')?></p>
          </article>
        <?php endforeach; ?>

          <article class="list">
            <a href="<?=App::base( App::xlat( $month['type'].'_singular' ) )?>">
              
            </a>
          </article>

      <?php else: ?>
        <p> No se han encontrado eventos para este mes </p>
      <?php endif; ?>
    </div>

  </div>
</div>